export {
  SITE_URL,
  SITE_NAME,
  getLocalizedUrl,
  generateHreflangAlternates,
  getOgLocale,
  getOgImageUrl,
  generateBaseMetadata,
  generateToolMetadata,
  generateArticleMetadata,
  generateBlogPostMetadata,
  generateToolJsonLd,
  generateToolHowToJsonLd,
  generateToolFaqJsonLd,
  generateNewsArticleJsonLd,
  generateBlogArticleJsonLd,
} from './seo/index'
