stages:
  - build
  - deploy

variables:
  NODE_ENV: production

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build
  only:
    - main

deploy:
  stage: deploy
  image: node:20
  dependencies:
    - build
  before_script:
    - npm install -g vercel
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  environment:
    name: production
    url: https://vaxtimyoxdu.com
  only:
    - main
