import { Tool } from '@/types/tool'

export const tools: Tool[] = [
  // AI Tools
  {
    slug: 'ai-text-rewriter',
    name: 'AI Text Rewriter',
    description: 'Rewrite and paraphrase your text using AI. Change tone, simplify language, or make text more professional. Free AI-powered text rewriter.',
    shortDescription: 'Rewrite text with AI-powered paraphrasing',
    category: 'ai',
    icon: '✍️',
    isAI: true,
    isClientSide: false,
    keywords: ['text rewriter', 'paraphrase', 'reword', 'ai rewriter'],
  },
  {
    slug: 'ai-text-summarizer',
    name: 'AI Text Summarizer',
    description: 'Summarize long text, articles, and documents using AI. Get concise summaries with key points. Free AI-powered summarizer.',
    shortDescription: 'Summarize text with AI',
    category: 'ai',
    icon: '📝',
    isAI: true,
    isClientSide: false,
    keywords: ['text summarizer', 'summarize', 'ai summary', 'tldr'],
  },
  {
    slug: 'ai-grammar-checker',
    name: 'AI Grammar Checker',
    description: 'Check and fix grammar, spelling, and punctuation errors using AI. Get instant corrections for your text. Free online grammar checker.',
    shortDescription: 'Fix grammar and spelling with AI',
    category: 'ai',
    icon: '✅',
    isAI: true,
    isClientSide: false,
    keywords: ['grammar checker', 'spell check', 'punctuation', 'proofreader'],
  },
  // PDF Tools
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Merge multiple PDF files into one document online. Rearrange pages, combine PDFs in any order. Free client-side PDF merger - your files never leave your browser.',
    shortDescription: 'Combine multiple PDFs into one',
    category: 'pdf',
    icon: '📑',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf merge', 'combine pdf', 'join pdf', 'pdf combiner'],
  },
  // Image Tools
  {
    slug: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress and resize images online. Reduce file size while maintaining quality. Supports JPEG, PNG, and WebP. Free client-side image compression.',
    shortDescription: 'Compress images to reduce file size',
    category: 'image',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['image compress', 'image resize', 'reduce image size', 'image optimizer'],
  },
  {
    slug: 'image-convert',
    name: 'Image Converter',
    description: 'Convert images between JPEG, PNG, and WebP formats online. Free client-side image converter - your files stay in your browser.',
    shortDescription: 'Convert images between formats',
    category: 'image',
    icon: '🔄',
    isAI: false,
    isClientSide: true,
    keywords: ['image converter', 'png to jpg', 'jpg to png', 'webp converter'],
  },
  // Developer Tools
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify your JSON data online. Minify or prettify JSON with syntax highlighting. Free JSON formatter with error detection.',
    shortDescription: 'Format, validate, and beautify JSON',
    category: 'dev',
    icon: '{ }',
    isAI: false,
    isClientSide: true,
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minifier'],
  },
  {
    slug: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode text to Base64 or decode Base64 strings online. Supports UTF-8 text and file encoding. Free Base64 converter tool.',
    shortDescription: 'Encode and decode Base64 strings',
    category: 'dev',
    icon: '🔐',
    isAI: false,
    isClientSide: true,
    keywords: ['base64', 'encode', 'decode', 'base64 converter'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions online with real-time matching. Highlight matches, view groups, and test regex patterns. Free regex tester tool.',
    shortDescription: 'Test regex patterns with live matching',
    category: 'dev',
    icon: '🔍',
    isAI: false,
    isClientSide: true,
    keywords: ['regex tester', 'regular expression', 'regex debugger', 'regex matcher'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes from text online. Free cryptographic hash generator tool.',
    shortDescription: 'Generate SHA hashes from text',
    category: 'dev',
    icon: '#️⃣',
    isAI: false,
    isClientSide: true,
    keywords: ['hash generator', 'sha256', 'sha512', 'hash calculator'],
  },
  // Generators
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and more. Download as PNG or SVG. Free online QR code maker with customizable size and colors.',
    shortDescription: 'Generate QR codes for any text or URL',
    category: 'generators',
    icon: '📱',
    isAI: false,
    isClientSide: true,
    keywords: ['qr code', 'qr generator', 'barcode', 'qr maker'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker & Palette Generator',
    description: 'Pick colors, convert between HEX, RGB, HSL formats, and generate beautiful color palettes. Free online color picker tool for designers.',
    shortDescription: 'Pick colors and generate palettes',
    category: 'generators',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['color picker', 'color palette', 'hex to rgb', 'color converter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate lorem ipsum placeholder text for your designs and mockups. Choose paragraphs, sentences, or words. Free dummy text generator.',
    shortDescription: 'Generate placeholder text',
    category: 'generators',
    icon: '📄',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
  },
  // Text Tools
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Estimate reading time. Free online word counter tool for writers and students.',
    shortDescription: 'Count words, characters, and more',
    category: 'text',
    icon: '🔢',
    isAI: false,
    isClientSide: true,
    keywords: ['word counter', 'character counter', 'text counter', 'word count'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case and more. Free online text case converter.',
    shortDescription: 'Convert text between different cases',
    category: 'text',
    icon: 'Aa',
    isAI: false,
    isClientSide: true,
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake case'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate clean URL slugs from any text. Remove special characters, handle accents, and create SEO-friendly URLs. Free online slug generator.',
    shortDescription: 'Generate URL-friendly slugs from text',
    category: 'text',
    icon: '🔗',
    isAI: false,
    isClientSide: true,
    keywords: ['slug generator', 'url slug', 'permalink', 'seo url'],
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and find differences. Highlight additions, deletions, and changes line by line. Free online text comparison tool.',
    shortDescription: 'Compare two texts and find differences',
    category: 'text',
    icon: '📊',
    isAI: false,
    isClientSide: true,
    keywords: ['text diff', 'text compare', 'diff checker', 'find differences'],
  },
  {
    slug: 'html-entity-codec',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode special characters to HTML entities or decode HTML entities back to text. Supports named and numeric entities. Free online tool.',
    shortDescription: 'Encode and decode HTML entities',
    category: 'text',
    icon: '&lt;',
    isAI: false,
    isClientSide: true,
    keywords: ['html entity', 'html encode', 'html decode', 'special characters'],
  },
  // New Developer Tools
  {
    slug: 'url-encode-decode',
    name: 'URL Encode/Decode',
    description: 'Encode or decode URL strings online. Convert special characters to percent-encoding or decode percent-encoded URLs. Free URL encoder/decoder.',
    shortDescription: 'Encode and decode URL strings',
    category: 'dev',
    icon: '🌐',
    isAI: false,
    isClientSide: true,
    keywords: ['url encode', 'url decode', 'percent encoding', 'urlencode'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) online. View header, payload, and expiration status. Free JWT decoder - no data sent to server.',
    shortDescription: 'Decode and inspect JWT tokens',
    category: 'dev',
    icon: '🎫',
    isAI: false,
    isClientSide: true,
    keywords: ['jwt decoder', 'jwt parser', 'json web token', 'token decoder'],
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write and preview Markdown in real-time. See formatted output as you type with support for headings, lists, code blocks, and more. Free online Markdown editor.',
    shortDescription: 'Write and preview Markdown in real-time',
    category: 'dev',
    icon: '📋',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown preview', 'markdown editor', 'md preview', 'markdown to html'],
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. View current timestamp, support for seconds and milliseconds. Free timestamp tool.',
    shortDescription: 'Convert between Unix timestamps and dates',
    category: 'dev',
    icon: '⏰',
    isAI: false,
    isClientSide: true,
    keywords: ['timestamp converter', 'unix timestamp', 'epoch converter', 'date converter'],
  },
  {
    slug: 'css-minifier',
    name: 'CSS Minifier & Beautifier',
    description: 'Minify CSS to reduce file size or beautify minified CSS for readability. See size savings. Free online CSS minifier and formatter.',
    shortDescription: 'Minify or beautify CSS code',
    category: 'dev',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['css minifier', 'css beautifier', 'css formatter', 'minify css'],
  },
  {
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between Binary, Octal, Decimal, and Hexadecimal. Real-time conversion with input validation. Free number base converter.',
    shortDescription: 'Convert between number bases',
    category: 'dev',
    icon: '🔢',
    isAI: false,
    isClientSide: true,
    keywords: ['number converter', 'binary', 'hexadecimal', 'octal', 'decimal'],
  },
  {
    slug: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format online. Supports custom delimiters, header rows, and quoted fields. Download or copy the JSON output.',
    shortDescription: 'Convert CSV data to JSON format',
    category: 'dev',
    icon: '📊',
    isAI: false,
    isClientSide: true,
    keywords: ['csv to json', 'csv converter', 'json converter', 'data converter'],
  },
  {
    slug: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and understand cron expressions. See human-readable descriptions and next execution times. Quick presets for common schedules.',
    shortDescription: 'Parse cron expressions to human-readable text',
    category: 'dev',
    icon: '⏱️',
    isAI: false,
    isClientSide: true,
    keywords: ['cron parser', 'cron expression', 'cron schedule', 'crontab'],
  },
  // New Generators
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with customizable length and character types. Password strength indicator included. Secure client-side generation.',
    shortDescription: 'Generate secure random passwords',
    category: 'generators',
    icon: '🔒',
    isAI: false,
    isClientSide: true,
    keywords: ['password generator', 'random password', 'secure password', 'strong password'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 identifiers online. Bulk generation, uppercase/lowercase options, with or without hyphens. Free UUID generator tool.',
    shortDescription: 'Generate UUID v4 identifiers',
    category: 'generators',
    icon: '🆔',
    isAI: false,
    isClientSide: true,
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'unique id'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO. Create Open Graph, Twitter Card, and standard meta tags with a live Google preview. Free meta tag generator.',
    shortDescription: 'Generate SEO meta tags for your website',
    category: 'generators',
    icon: '🏷️',
    isAI: false,
    isClientSide: true,
    keywords: ['meta tag generator', 'seo tags', 'open graph', 'twitter card'],
  },
  {
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and convert aspect ratios. Lock ratios, use common presets like 16:9 and 4:3, and find matching resolutions. Free aspect ratio tool.',
    shortDescription: 'Calculate and convert aspect ratios',
    category: 'generators',
    icon: '📐',
    isAI: false,
    isClientSide: true,
    keywords: ['aspect ratio', 'ratio calculator', 'screen ratio', 'resolution calculator'],
  },
]

export const categories: Record<string, { name: string; description: string }> = {
  ai: { name: 'AI Tools', description: 'AI-powered text processing' },
  pdf: { name: 'PDF Tools', description: 'Merge, compress, and convert PDF files' },
  image: { name: 'Image Tools', description: 'Compress, resize, and convert images' },
  dev: { name: 'Developer Tools', description: 'JSON, Base64, Regex, Hash, JWT, CSV and more for developers' },
  generators: { name: 'Generators', description: 'Generate passwords, UUIDs, QR codes, meta tags, colors' },
  text: { name: 'Text Tools', description: 'Case converter, diff checker, slug generator, word count' },
}
