import { Tool } from '@/types/tool'

export const tools: Tool[] = [
  // AI Tools
  {
    slug: 'ai-text-rewriter',
    name: 'AI Text Rewriter',
    description: 'Rewrite and paraphrase your text using AI. Change tone, simplify language, or make text more professional. Free AI-powered text rewriter.',
    shortDescription: 'Rewrite text with AI-powered paraphrasing',
    category: 'ai',
    icon: '✍️',
    isAI: true,
    isClientSide: false,
    keywords: ['text rewriter', 'paraphrase', 'reword', 'ai rewriter'],
  },
  {
    slug: 'ai-text-summarizer',
    name: 'AI Text Summarizer',
    description: 'Summarize long text, articles, and documents using AI. Get concise summaries with key points. Free AI-powered summarizer.',
    shortDescription: 'Summarize text with AI',
    category: 'ai',
    icon: '📝',
    isAI: true,
    isClientSide: false,
    keywords: ['text summarizer', 'summarize', 'ai summary', 'tldr'],
  },
  {
    slug: 'ai-grammar-checker',
    name: 'AI Grammar Checker',
    description: 'Check and fix grammar, spelling, and punctuation errors using AI. Get instant corrections for your text. Free online grammar checker.',
    shortDescription: 'Fix grammar and spelling with AI',
    category: 'ai',
    icon: '✅',
    isAI: true,
    isClientSide: false,
    keywords: ['grammar checker', 'spell check', 'punctuation', 'proofreader'],
  },
  // PDF Tools
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Merge multiple PDF files into one document online. Rearrange pages, combine PDFs in any order. Free client-side PDF merger - your files never leave your browser.',
    shortDescription: 'Combine multiple PDFs into one',
    category: 'pdf',
    icon: '📑',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf merge', 'combine pdf', 'join pdf', 'pdf combiner'],
  },
  {
    slug: 'pdf-split',
    name: 'PDF Page Splitter',
    description: 'Extract specific pages from a PDF file online. Select page ranges to split and download. Free client-side PDF splitter - your files never leave your browser.',
    shortDescription: 'Extract specific pages from a PDF',
    category: 'pdf',
    icon: '✂️',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf split', 'pdf extract pages', 'pdf page splitter', 'split pdf'],
  },
  {
    slug: 'pdf-compress',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size online. Remove metadata and optimize structure to compress PDFs. Free client-side PDF compressor - your files never leave your browser.',
    shortDescription: 'Reduce PDF file size',
    category: 'pdf',
    icon: '📦',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf compress', 'reduce pdf size', 'pdf compressor', 'shrink pdf'],
  },
  // Image Tools
  {
    slug: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress and resize images online. Reduce file size while maintaining quality. Supports JPEG, PNG, and WebP. Free client-side image compression.',
    shortDescription: 'Compress images to reduce file size',
    category: 'image',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['image compress', 'image resize', 'reduce image size', 'image optimizer'],
  },
  {
    slug: 'image-convert',
    name: 'Image Converter',
    description: 'Convert images between JPEG, PNG, and WebP formats online. Free client-side image converter - your files stay in your browser.',
    shortDescription: 'Convert images between formats',
    category: 'image',
    icon: '🔄',
    isAI: false,
    isClientSide: true,
    keywords: ['image converter', 'png to jpg', 'jpg to png', 'webp converter'],
  },
  {
    slug: 'image-resize',
    name: 'Image Resizer',
    description: 'Resize images to exact dimensions or by percentage online. Maintain aspect ratio, supports JPEG, PNG, and WebP. Free client-side image resizer.',
    shortDescription: 'Resize images to exact dimensions',
    category: 'image',
    icon: '📐',
    isAI: false,
    isClientSide: true,
    keywords: ['image resize', 'resize image', 'image dimensions', 'scale image'],
  },
  {
    slug: 'image-crop',
    name: 'Image Cropper',
    description: 'Crop images with a drag-to-select area online. Select any region of your image and download the cropped result. Free client-side image cropper.',
    shortDescription: 'Crop images with drag-to-select',
    category: 'image',
    icon: '✂️',
    isAI: false,
    isClientSide: true,
    keywords: ['image crop', 'crop image', 'image cropper', 'cut image'],
  },
  // Developer Tools
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify your JSON data online. Minify or prettify JSON with syntax highlighting. Free JSON formatter with error detection.',
    shortDescription: 'Format, validate, and beautify JSON',
    category: 'dev',
    icon: '{ }',
    isAI: false,
    isClientSide: true,
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minifier'],
  },
  {
    slug: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode text to Base64 or decode Base64 strings online. Supports UTF-8 text and file encoding. Free Base64 converter tool.',
    shortDescription: 'Encode and decode Base64 strings',
    category: 'dev',
    icon: '🔐',
    isAI: false,
    isClientSide: true,
    keywords: ['base64', 'encode', 'decode', 'base64 converter'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions online with real-time matching. Highlight matches, view groups, and test regex patterns. Free regex tester tool.',
    shortDescription: 'Test regex patterns with live matching',
    category: 'dev',
    icon: '🔍',
    isAI: false,
    isClientSide: true,
    keywords: ['regex tester', 'regular expression', 'regex debugger', 'regex matcher'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes from text online. Free cryptographic hash generator tool.',
    shortDescription: 'Generate SHA hashes from text',
    category: 'dev',
    icon: '#️⃣',
    isAI: false,
    isClientSide: true,
    keywords: ['hash generator', 'sha256', 'sha512', 'hash calculator'],
  },
  // Generators
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and more. Download as PNG or SVG. Free online QR code maker with customizable size and colors.',
    shortDescription: 'Generate QR codes for any text or URL',
    category: 'generators',
    icon: '📱',
    isAI: false,
    isClientSide: true,
    keywords: ['qr code', 'qr generator', 'barcode', 'qr maker'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker & Palette Generator',
    description: 'Pick colors, convert between HEX, RGB, HSL formats, and generate beautiful color palettes. Free online color picker tool for designers.',
    shortDescription: 'Pick colors and generate palettes',
    category: 'generators',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['color picker', 'color palette', 'hex to rgb', 'color converter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate lorem ipsum placeholder text for your designs and mockups. Choose paragraphs, sentences, or words. Free dummy text generator.',
    shortDescription: 'Generate placeholder text',
    category: 'generators',
    icon: '📄',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
  },
  // Text Tools
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Estimate reading time. Free online word counter tool for writers and students.',
    shortDescription: 'Count words, characters, and more',
    category: 'text',
    icon: '🔢',
    isAI: false,
    isClientSide: true,
    keywords: ['word counter', 'character counter', 'text counter', 'word count'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case and more. Free online text case converter.',
    shortDescription: 'Convert text between different cases',
    category: 'text',
    icon: 'Aa',
    isAI: false,
    isClientSide: true,
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake case'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate clean URL slugs from any text. Remove special characters, handle accents, and create SEO-friendly URLs. Free online slug generator.',
    shortDescription: 'Generate URL-friendly slugs from text',
    category: 'text',
    icon: '🔗',
    isAI: false,
    isClientSide: true,
    keywords: ['slug generator', 'url slug', 'permalink', 'seo url'],
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and find differences. Highlight additions, deletions, and changes line by line. Free online text comparison tool.',
    shortDescription: 'Compare two texts and find differences',
    category: 'text',
    icon: '📊',
    isAI: false,
    isClientSide: true,
    keywords: ['text diff', 'text compare', 'diff checker', 'find differences'],
  },
  {
    slug: 'html-entity-codec',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode special characters to HTML entities or decode HTML entities back to text. Supports named and numeric entities. Free online tool.',
    shortDescription: 'Encode and decode HTML entities',
    category: 'text',
    icon: '&lt;',
    isAI: false,
    isClientSide: true,
    keywords: ['html entity', 'html encode', 'html decode', 'special characters'],
  },
  // New Developer Tools
  {
    slug: 'url-encode-decode',
    name: 'URL Encode/Decode',
    description: 'Encode or decode URL strings online. Convert special characters to percent-encoding or decode percent-encoded URLs. Free URL encoder/decoder.',
    shortDescription: 'Encode and decode URL strings',
    category: 'dev',
    icon: '🌐',
    isAI: false,
    isClientSide: true,
    keywords: ['url encode', 'url decode', 'percent encoding', 'urlencode'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) online. View header, payload, and expiration status. Free JWT decoder - no data sent to server.',
    shortDescription: 'Decode and inspect JWT tokens',
    category: 'dev',
    icon: '🎫',
    isAI: false,
    isClientSide: true,
    keywords: ['jwt decoder', 'jwt parser', 'json web token', 'token decoder'],
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write and preview Markdown in real-time. See formatted output as you type with support for headings, lists, code blocks, and more. Free online Markdown editor.',
    shortDescription: 'Write and preview Markdown in real-time',
    category: 'dev',
    icon: '📋',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown preview', 'markdown editor', 'md preview', 'markdown to html'],
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. View current timestamp, support for seconds and milliseconds. Free timestamp tool.',
    shortDescription: 'Convert between Unix timestamps and dates',
    category: 'dev',
    icon: '⏰',
    isAI: false,
    isClientSide: true,
    keywords: ['timestamp converter', 'unix timestamp', 'epoch converter', 'date converter'],
  },
  {
    slug: 'css-minifier',
    name: 'CSS Minifier & Beautifier',
    description: 'Minify CSS to reduce file size or beautify minified CSS for readability. See size savings. Free online CSS minifier and formatter.',
    shortDescription: 'Minify or beautify CSS code',
    category: 'dev',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['css minifier', 'css beautifier', 'css formatter', 'minify css'],
  },
  {
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between Binary, Octal, Decimal, and Hexadecimal. Real-time conversion with input validation. Free number base converter.',
    shortDescription: 'Convert between number bases',
    category: 'dev',
    icon: '🔢',
    isAI: false,
    isClientSide: true,
    keywords: ['number converter', 'binary', 'hexadecimal', 'octal', 'decimal'],
  },
  {
    slug: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format online. Supports custom delimiters, header rows, and quoted fields. Download or copy the JSON output.',
    shortDescription: 'Convert CSV data to JSON format',
    category: 'dev',
    icon: '📊',
    isAI: false,
    isClientSide: true,
    keywords: ['csv to json', 'csv converter', 'json converter', 'data converter'],
  },
  {
    slug: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and understand cron expressions. See human-readable descriptions and next execution times. Quick presets for common schedules.',
    shortDescription: 'Parse cron expressions to human-readable text',
    category: 'dev',
    icon: '⏱️',
    isAI: false,
    isClientSide: true,
    keywords: ['cron parser', 'cron expression', 'cron schedule', 'crontab'],
  },
  {
    slug: 'html-minifier',
    name: 'HTML Minifier & Beautifier',
    description: 'Minify HTML to reduce file size or beautify minified HTML for readability. Remove comments and whitespace. Free online HTML minifier and formatter.',
    shortDescription: 'Minify or beautify HTML code',
    category: 'dev',
    icon: '🌐',
    isAI: false,
    isClientSide: true,
    keywords: ['html minifier', 'html beautifier', 'html formatter', 'minify html'],
  },
  {
    slug: 'js-minifier',
    name: 'JavaScript Minifier & Beautifier',
    description: 'Minify JavaScript to reduce file size or beautify minified JS for readability. Remove comments and whitespace. Free online JS minifier and formatter.',
    shortDescription: 'Minify or beautify JavaScript code',
    category: 'dev',
    icon: '⚡',
    isAI: false,
    isClientSide: true,
    keywords: ['js minifier', 'javascript minifier', 'js beautifier', 'minify javascript'],
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries online. Indent keywords, align clauses, and make your SQL readable. Free online SQL formatter tool.',
    shortDescription: 'Format and beautify SQL queries',
    category: 'dev',
    icon: '🗃️',
    isAI: false,
    isClientSide: true,
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql pretty print'],
  },
  {
    slug: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert JSON arrays to CSV format online. Supports custom delimiters and download. Free JSON to CSV converter tool.',
    shortDescription: 'Convert JSON arrays to CSV format',
    category: 'dev',
    icon: '📊',
    isAI: false,
    isClientSide: true,
    keywords: ['json to csv', 'json converter', 'csv converter', 'convert json'],
  },
  {
    slug: 'ip-address-info',
    name: 'IP Address Info',
    description: 'View your public IP address, user agent, screen resolution, and browser information. Free online IP and device info tool.',
    shortDescription: 'View your IP and browser information',
    category: 'dev',
    icon: '🌍',
    isAI: false,
    isClientSide: true,
    keywords: ['ip address', 'my ip', 'user agent', 'browser info', 'what is my ip'],
  },
  // New Generators
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with customizable length and character types. Password strength indicator included. Secure client-side generation.',
    shortDescription: 'Generate secure random passwords',
    category: 'generators',
    icon: '🔒',
    isAI: false,
    isClientSide: true,
    keywords: ['password generator', 'random password', 'secure password', 'strong password'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 identifiers online. Bulk generation, uppercase/lowercase options, with or without hyphens. Free UUID generator tool.',
    shortDescription: 'Generate UUID v4 identifiers',
    category: 'generators',
    icon: '🆔',
    isAI: false,
    isClientSide: true,
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'unique id'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO. Create Open Graph, Twitter Card, and standard meta tags with a live Google preview. Free meta tag generator.',
    shortDescription: 'Generate SEO meta tags for your website',
    category: 'generators',
    icon: '🏷️',
    isAI: false,
    isClientSide: true,
    keywords: ['meta tag generator', 'seo tags', 'open graph', 'twitter card'],
  },
  {
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and convert aspect ratios. Lock ratios, use common presets like 16:9 and 4:3, and find matching resolutions. Free aspect ratio tool.',
    shortDescription: 'Calculate and convert aspect ratios',
    category: 'generators',
    icon: '📐',
    isAI: false,
    isClientSide: true,
    keywords: ['aspect ratio', 'ratio calculator', 'screen ratio', 'resolution calculator'],
  },
  {
    slug: 'emoji-picker',
    name: 'Emoji Picker & Search',
    description: 'Browse, search, and copy emojis by category. Click any emoji to copy it to your clipboard instantly. Free online emoji picker.',
    shortDescription: 'Browse and copy emojis by category',
    category: 'generators',
    icon: '😀',
    isAI: false,
    isClientSide: true,
    keywords: ['emoji picker', 'emoji search', 'copy emoji', 'emoji keyboard'],
  },
  {
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful linear and radial CSS gradients with multiple color stops. Preview in real-time and copy the CSS code. Free gradient generator.',
    shortDescription: 'Create CSS gradients with color stops',
    category: 'generators',
    icon: '🌈',
    isAI: false,
    isClientSide: true,
    keywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient'],
  },
  {
    slug: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images with custom dimensions, colors, and text. Download as PNG or JPEG. Free online placeholder image maker.',
    shortDescription: 'Generate placeholder images with custom size',
    category: 'generators',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['placeholder image', 'dummy image', 'placeholder generator', 'test image'],
  },
  // New Text Tools
  {
    slug: 'text-to-binary',
    name: 'Text to Binary Converter',
    description: 'Convert text to binary, hexadecimal, or octal and vice versa. Free online text to binary converter with multiple encoding formats.',
    shortDescription: 'Convert text to binary, hex, or octal',
    category: 'text',
    icon: '💻',
    isAI: false,
    isClientSide: true,
    keywords: ['text to binary', 'binary converter', 'hex converter', 'octal converter'],
  },
  {
    slug: 'rot13-encoder',
    name: 'ROT13 Encoder/Decoder',
    description: 'Encode and decode text using ROT13 Caesar cipher. Supports custom shift values from 1 to 25. Free online ROT13 encoder tool.',
    shortDescription: 'ROT13 and Caesar cipher encoder/decoder',
    category: 'text',
    icon: '🔄',
    isAI: false,
    isClientSide: true,
    keywords: ['rot13', 'caesar cipher', 'rot13 encoder', 'cipher decoder'],
  },
  {
    slug: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Focus timer using the Pomodoro Technique. 25-minute work sessions with 5-minute breaks. Sound notifications and session tracking. Free online timer.',
    shortDescription: '25/5 minute work/break focus timer',
    category: 'text',
    icon: '⏱️',
    isAI: false,
    isClientSide: true,
    keywords: ['pomodoro timer', 'focus timer', 'work timer', 'productivity timer'],
  },
  // New Developer Tools (Phase 7)
  {
    slug: 'json-to-yaml',
    name: 'JSON to YAML Converter',
    description: 'Convert JSON to YAML and YAML to JSON online. Bidirectional conversion with proper formatting and syntax. Free client-side JSON/YAML converter tool.',
    shortDescription: 'Convert between JSON and YAML formats',
    category: 'dev',
    icon: '🔀',
    isAI: false,
    isClientSide: true,
    keywords: ['json to yaml', 'yaml to json', 'yaml converter', 'json converter', 'data format'],
  },
  {
    slug: 'xml-formatter',
    name: 'XML Formatter & Validator',
    description: 'Format, minify, and validate XML online. Beautify XML with custom indentation, validate tag matching, and minify for production. Free XML formatter tool.',
    shortDescription: 'Format, minify, and validate XML',
    category: 'dev',
    icon: '📰',
    isAI: false,
    isClientSide: true,
    keywords: ['xml formatter', 'xml validator', 'xml beautifier', 'xml minifier', 'format xml'],
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    description: 'Convert Markdown to HTML with a live preview. Supports headings, bold, italic, links, code blocks, lists, blockquotes, and more. Free Markdown converter.',
    shortDescription: 'Convert Markdown to HTML with live preview',
    category: 'dev',
    icon: '📝',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown to html', 'markdown converter', 'md to html', 'markdown parser', 'html generator'],
  },
  // New Generators (Phase 7)
  {
    slug: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Upload an image and generate favicons in multiple sizes (16x16 to 512x512). Download individually or as a ZIP. Free client-side favicon generator.',
    shortDescription: 'Generate multi-size favicons from an image',
    category: 'generators',
    icon: '⭐',
    isAI: false,
    isClientSide: true,
    keywords: ['favicon generator', 'favicon maker', 'ico generator', 'website icon', 'app icon'],
  },
  {
    slug: 'svg-to-png',
    name: 'SVG to PNG Converter',
    description: 'Convert SVG to PNG with custom dimensions online. Paste SVG code or upload a file, set width and height, and download as PNG. Free client-side converter.',
    shortDescription: 'Convert SVG to PNG with custom dimensions',
    category: 'generators',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['svg to png', 'svg converter', 'svg to image', 'convert svg', 'png generator'],
  },
  // New Text Tools (Phase 7)
  {
    slug: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to speech using the Web Speech API. Choose from available voices, adjust speed, pitch, and volume. Free online text-to-speech reader.',
    shortDescription: 'Read text aloud with voice controls',
    category: 'text',
    icon: '🔊',
    isAI: false,
    isClientSide: true,
    keywords: ['text to speech', 'tts', 'read aloud', 'speech synthesis', 'voice reader'],
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, words, sentences, paragraphs, and lines. View reading time, speaking time, character frequency, and more. Free detailed text analysis tool.',
    shortDescription: 'Detailed character and text statistics',
    category: 'text',
    icon: '🔤',
    isAI: false,
    isClientSide: true,
    keywords: ['character counter', 'letter counter', 'text statistics', 'reading time', 'speaking time'],
  },
  {
    slug: 'find-and-replace',
    name: 'Find and Replace',
    description: 'Find and replace text with regex support, case sensitivity, and whole word matching. Highlights all matches in real-time. Free online find and replace tool.',
    shortDescription: 'Find and replace text with regex support',
    category: 'text',
    icon: '🔍',
    isAI: false,
    isClientSide: true,
    keywords: ['find and replace', 'search replace', 'text replace', 'regex replace', 'find text'],
  },
  // New Developer Tools (Phase 8)
  {
    slug: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Parse and convert YAML to JSON online with validation and error highlighting. Supports nested objects, arrays, comments, and inline collections. Free client-side YAML parser.',
    shortDescription: 'Parse YAML and convert to JSON format',
    category: 'dev',
    icon: '📋',
    isAI: false,
    isClientSide: true,
    keywords: ['yaml to json', 'yaml parser', 'yaml converter', 'yaml validator', 'convert yaml'],
  },
  {
    slug: 'http-status-codes',
    name: 'HTTP Status Code Reference',
    description: 'Searchable reference of all HTTP status codes with descriptions, categories (1xx-5xx), and usage examples. Filter by category or search by code and name. Free HTTP status code lookup.',
    shortDescription: 'Searchable HTTP status code reference guide',
    category: 'dev',
    icon: '🌐',
    isAI: false,
    isClientSide: true,
    keywords: ['http status codes', 'status code reference', 'http codes', 'http error codes', 'rest api codes'],
  },
  // New Generators (Phase 8)
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units of length, weight, temperature, speed, digital storage, time, and area. Supports metric and imperial units with instant conversion. Free online unit converter.',
    shortDescription: 'Convert between measurement units',
    category: 'generators',
    icon: '📏',
    isAI: false,
    isClientSide: true,
    keywords: ['unit converter', 'measurement converter', 'metric converter', 'imperial converter', 'length converter'],
  },
  {
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices with company details, line items, tax calculation, and totals. Preview and download as PDF using browser print. Free online invoice maker.',
    shortDescription: 'Create and download professional invoices',
    category: 'generators',
    icon: '🧾',
    isAI: false,
    isClientSide: true,
    keywords: ['invoice generator', 'invoice maker', 'invoice creator', 'billing', 'invoice pdf'],
  },
  // New Text Tools (Phase 8)
  {
    slug: 'morse-code',
    name: 'Morse Code Translator',
    description: 'Convert text to Morse code and Morse code to text. Includes audio playback using Web Audio API, reference chart, and bidirectional translation. Free online Morse code translator.',
    shortDescription: 'Translate text to and from Morse code',
    category: 'text',
    icon: '📡',
    isAI: false,
    isClientSide: true,
    keywords: ['morse code', 'morse translator', 'morse code converter', 'morse audio', 'dot dash'],
  },
  {
    slug: 'random-text-generator',
    name: 'Random Text Generator',
    description: 'Generate random words, sentences, paragraphs, names, email addresses, phone numbers, and addresses for testing and mockup purposes. Free random data generator.',
    shortDescription: 'Generate random text and mock data',
    category: 'text',
    icon: '🎲',
    isAI: false,
    isClientSide: true,
    keywords: ['random text', 'random generator', 'mock data', 'test data', 'random names', 'random emails'],
  },
  {
    slug: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat text N times with custom separator, prefix, suffix, and numbering options. Choose from various separators and number formats. Free online text repeater tool.',
    shortDescription: 'Repeat text with custom separators and numbering',
    category: 'text',
    icon: '🔁',
    isAI: false,
    isClientSide: true,
    keywords: ['text repeater', 'repeat text', 'text multiplier', 'copy paste repeat', 'duplicate text'],
  },
  // Market Tracker
  {
    slug: 'market-tracker',
    name: 'Market Price Tracker',
    description: 'Track live prices of Bitcoin, Ethereum, Gold, and Oil. See 24-hour price changes, convert between currencies (USD, AZN, EUR), and view market summaries. Free real-time market tracker.',
    shortDescription: 'Live crypto, gold & oil price tracker',
    category: 'generators',
    icon: '\uD83D\uDCC8',
    isAI: false,
    isClientSide: false,
    keywords: ['market tracker', 'bitcoin price', 'crypto prices', 'gold price', 'oil price', 'market prices', 'price tracker'],
  },
  // Phase 9 - New Tools (70 total)
  // New Generators
  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Extract animated clips from video files using browser APIs. Set start time, duration, FPS, and resolution. Free client-side video to animation converter.',
    shortDescription: 'Extract animated clips from video files',
    category: 'generators',
    icon: '🎬',
    isAI: false,
    isClientSide: true,
    keywords: ['video to gif', 'gif maker', 'video converter', 'animated gif', 'video clip'],
  },
  {
    slug: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a base color. Supports complementary, analogous, triadic, tetradic, split-complementary, and monochromatic harmonies. Export as CSS variables.',
    shortDescription: 'Generate harmonious color palettes',
    category: 'generators',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['color palette', 'color scheme', 'color harmony', 'complementary colors', 'color generator'],
  },
  {
    slug: 'backlink-generator',
    name: 'Backlink Generator',
    description: 'Generate backlinks in multiple formats: HTML, Markdown, BBCode, Textile, Wiki, and reStructuredText. Configure rel attributes, target, and anchor text. Free link code generator.',
    shortDescription: 'Generate links in HTML, Markdown, BBCode, and more',
    category: 'generators',
    icon: '🔗',
    isAI: false,
    isClientSide: true,
    keywords: ['backlink generator', 'link generator', 'html link', 'markdown link', 'bbcode link'],
  },
  // New Developer Tools
  {
    slug: 'json-path-finder',
    name: 'JSON Path Finder',
    description: 'Navigate JSON structure with an interactive tree view. Click nodes to find their JSON path. Query values by path expression. Free JSON path explorer tool.',
    shortDescription: 'Navigate JSON and find paths interactively',
    category: 'dev',
    icon: '🔎',
    isAI: false,
    isClientSide: true,
    keywords: ['json path', 'json navigator', 'json tree', 'json explorer', 'jsonpath'],
  },
  {
    slug: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Unix file permissions with an interactive grid. Convert between octal (755) and symbolic (rwxr-xr-x) notation. Common permission presets included. Free chmod calculator.',
    shortDescription: 'Unix file permissions calculator (rwx to octal)',
    category: 'dev',
    icon: '🔐',
    isAI: false,
    isClientSide: true,
    keywords: ['chmod calculator', 'file permissions', 'unix permissions', 'rwx', 'octal permissions'],
  },
  {
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create Markdown tables with a visual editor. Add rows and columns, set alignment, and copy the generated Markdown. Free online Markdown table maker.',
    shortDescription: 'Create Markdown tables with a visual editor',
    category: 'dev',
    icon: '📋',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown table', 'table generator', 'markdown editor', 'table maker', 'md table'],
  },
  {
    slug: 'regex-library',
    name: 'Regex Pattern Library',
    description: 'Browse and search a curated library of common regex patterns for emails, URLs, dates, numbers, and more. Test patterns against your input. Free regex reference.',
    shortDescription: 'Curated library of common regex patterns',
    category: 'dev',
    icon: '📚',
    isAI: false,
    isClientSide: true,
    keywords: ['regex library', 'regex patterns', 'regex reference', 'regular expression', 'regex examples'],
  },
  // New Image Tools
  {
    slug: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings. Output as Data URI, raw Base64, CSS background, or HTML img tag. Supports JPEG, PNG, GIF, WebP, SVG. Free client-side converter.',
    shortDescription: 'Convert images to Base64 strings',
    category: 'image',
    icon: '🔣',
    isAI: false,
    isClientSide: true,
    keywords: ['image to base64', 'base64 image', 'data uri', 'image encoder', 'base64 converter'],
  },
  {
    slug: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Decode Base64 strings back to images. Auto-detects JPEG, PNG, GIF, WebP, and SVG formats. Preview and download the decoded image. Free client-side decoder.',
    shortDescription: 'Decode Base64 strings to images',
    category: 'image',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['base64 to image', 'decode base64', 'image decoder', 'data uri to image', 'base64 viewer'],
  },
  // New Text Tool
  {
    slug: 'text-truncator',
    name: 'Text Truncator',
    description: 'Truncate text by characters, words, or sentences with customizable ellipsis. Choose ellipsis position (start, middle, end) and preserve whole words. Free text truncation tool.',
    shortDescription: 'Truncate text by characters, words, or sentences',
    category: 'text',
    icon: '✂️',
    isAI: false,
    isClientSide: true,
    keywords: ['text truncator', 'truncate text', 'shorten text', 'text cutter', 'text ellipsis'],
  },
]

export const categories: Record<string, { name: string; description: string }> = {
  ai: { name: 'AI Tools', description: 'AI-powered text processing' },
  pdf: { name: 'PDF Tools', description: 'Merge, split, compress PDF files' },
  image: { name: 'Image Tools', description: 'Compress, resize, crop, and convert images' },
  dev: { name: 'Developer Tools', description: 'JSON, Base64, Regex, SQL, HTML, JS, CSV and more for developers' },
  generators: { name: 'Generators', description: 'Generate passwords, UUIDs, QR codes, gradients, emojis, colors' },
  text: { name: 'Text Tools', description: 'Case converter, binary, ROT13, diff checker, timer, word count' },
}
