import { Tool } from '@/types/tool'

export const tools: Tool[] = [
  // AI Tools
  {
    slug: 'ai-text-rewriter',
    name: 'AI Text Rewriter',
    description: 'Rewrite and paraphrase your text using AI. Change tone, simplify language, or make text more professional. Free AI-powered text rewriter.',
    shortDescription: 'Rewrite text with AI-powered paraphrasing',
    category: 'ai',
    icon: '✍️',
    isAI: true,
    isClientSide: false,
    keywords: ['text rewriter', 'paraphrase', 'reword', 'ai rewriter'],
  },
  {
    slug: 'ai-text-summarizer',
    name: 'AI Text Summarizer',
    description: 'Summarize long text, articles, and documents using AI. Get concise summaries with key points. Free AI-powered summarizer.',
    shortDescription: 'Summarize text with AI',
    category: 'ai',
    icon: '📝',
    isAI: true,
    isClientSide: false,
    keywords: ['text summarizer', 'summarize', 'ai summary', 'tldr'],
  },
  {
    slug: 'ai-grammar-checker',
    name: 'AI Grammar Checker',
    description: 'Check and fix grammar, spelling, and punctuation errors using AI. Get instant corrections for your text. Free online grammar checker.',
    shortDescription: 'Fix grammar and spelling with AI',
    category: 'ai',
    icon: '✅',
    isAI: true,
    isClientSide: false,
    keywords: ['grammar checker', 'spell check', 'punctuation', 'proofreader'],
  },
  // PDF Tools
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Merge multiple PDF files into one document online. Rearrange pages, combine PDFs in any order. Free client-side PDF merger - your files never leave your browser.',
    shortDescription: 'Combine multiple PDFs into one',
    category: 'pdf',
    icon: '📑',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf merge', 'combine pdf', 'join pdf', 'pdf combiner'],
  },
  // Image Tools
  {
    slug: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress and resize images online. Reduce file size while maintaining quality. Supports JPEG, PNG, and WebP. Free client-side image compression.',
    shortDescription: 'Compress images to reduce file size',
    category: 'image',
    icon: '🖼️',
    isAI: false,
    isClientSide: true,
    keywords: ['image compress', 'image resize', 'reduce image size', 'image optimizer'],
  },
  {
    slug: 'image-convert',
    name: 'Image Converter',
    description: 'Convert images between JPEG, PNG, and WebP formats online. Free client-side image converter - your files stay in your browser.',
    shortDescription: 'Convert images between formats',
    category: 'image',
    icon: '🔄',
    isAI: false,
    isClientSide: true,
    keywords: ['image converter', 'png to jpg', 'jpg to png', 'webp converter'],
  },
  // Developer Tools
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify your JSON data online. Minify or prettify JSON with syntax highlighting. Free JSON formatter with error detection.',
    shortDescription: 'Format, validate, and beautify JSON',
    category: 'dev',
    icon: '{ }',
    isAI: false,
    isClientSide: true,
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minifier'],
  },
  {
    slug: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode text to Base64 or decode Base64 strings online. Supports UTF-8 text and file encoding. Free Base64 converter tool.',
    shortDescription: 'Encode and decode Base64 strings',
    category: 'dev',
    icon: '🔐',
    isAI: false,
    isClientSide: true,
    keywords: ['base64', 'encode', 'decode', 'base64 converter'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions online with real-time matching. Highlight matches, view groups, and test regex patterns. Free regex tester tool.',
    shortDescription: 'Test regex patterns with live matching',
    category: 'dev',
    icon: '🔍',
    isAI: false,
    isClientSide: true,
    keywords: ['regex tester', 'regular expression', 'regex debugger', 'regex matcher'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes from text online. Free cryptographic hash generator tool.',
    shortDescription: 'Generate SHA hashes from text',
    category: 'dev',
    icon: '#️⃣',
    isAI: false,
    isClientSide: true,
    keywords: ['hash generator', 'sha256', 'sha512', 'hash calculator'],
  },
  // Generators
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and more. Download as PNG or SVG. Free online QR code maker with customizable size and colors.',
    shortDescription: 'Generate QR codes for any text or URL',
    category: 'generators',
    icon: '📱',
    isAI: false,
    isClientSide: true,
    keywords: ['qr code', 'qr generator', 'barcode', 'qr maker'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker & Palette Generator',
    description: 'Pick colors, convert between HEX, RGB, HSL formats, and generate beautiful color palettes. Free online color picker tool for designers.',
    shortDescription: 'Pick colors and generate palettes',
    category: 'generators',
    icon: '🎨',
    isAI: false,
    isClientSide: true,
    keywords: ['color picker', 'color palette', 'hex to rgb', 'color converter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate lorem ipsum placeholder text for your designs and mockups. Choose paragraphs, sentences, or words. Free dummy text generator.',
    shortDescription: 'Generate placeholder text',
    category: 'generators',
    icon: '📄',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
  },
  // Text Tools
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Estimate reading time. Free online word counter tool for writers and students.',
    shortDescription: 'Count words, characters, and more',
    category: 'text',
    icon: '🔢',
    isAI: false,
    isClientSide: true,
    keywords: ['word counter', 'character counter', 'text counter', 'word count'],
  },
]

export const categories: Record<string, { name: string; description: string }> = {
  ai: { name: 'AI Tools', description: 'AI-powered text processing' },
  pdf: { name: 'PDF Tools', description: 'Merge, compress, and convert PDF files' },
  image: { name: 'Image Tools', description: 'Compress, resize, and convert images' },
  dev: { name: 'Developer Tools', description: 'JSON, Base64, Regex, Hash tools for developers' },
  generators: { name: 'Generators', description: 'Generate QR codes, colors, text' },
  text: { name: 'Text Tools', description: 'Word count, text analysis' },
}
