import { Tool } from '@/types/tool'

export const devTools: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify your JSON data online. Minify or prettify JSON with syntax highlighting. Free JSON formatter with error detection.',
    shortDescription: 'Format, validate, and beautify JSON',
    category: 'dev',
    icon: '{ }',
    isAI: false,
    isClientSide: true,
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minifier'],
    metaTitle: {
      az: 'Pulsuz JSON Formatlayıcı və Validator | Brauzerdə',
      en: 'JSON Formatter, Validator & Beautifier — Free',
      tr: 'Ücretsiz JSON Biçimlendirici & Doğrulayıcı | Anlık',
      ru: 'Бесплатный JSON Форматтер & Валидатор | В браузере',
    },
    metaDescription: {
      az: 'JSON-u brauzerində formatla, doğrula, kiçilt və ya gözəl göstər. Sintaksis rəngi, xəta vurğulaması. Məlumat serverə göndərilmir.',
      en: 'Format, validate, minify or prettify JSON in your browser. Syntax highlighting, error detection. Your data never leaves your device.',
      tr: 'JSON\'u tarayıcında biçimlendir, doğrula, küçült veya güzelleştir. Söz dizimi renklendirme, hata tespiti. Verin cihazından çıkmaz.',
      ru: 'Форматируй, валидируй, минифицируй или украшай JSON в браузере. Подсветка синтаксиса, ошибки. Данные не покидают устройство.',
    },
  },
  {
    slug: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode text to Base64 or decode Base64 strings online. Supports UTF-8 text and file encoding. Free Base64 converter tool.',
    shortDescription: 'Encode and decode Base64 strings',
    category: 'dev',
    icon: '\uD83D\uDD10',
    isAI: false,
    isClientSide: true,
    keywords: ['base64', 'encode', 'decode', 'base64 converter'],
    metaTitle: {
      az: 'Base64 Kodla/Dekodla — Pulsuz, Brauzerdə',
      en: 'Base64 Encode & Decode — Free, Instant, Private',
      tr: 'Base64 Kodla/Çöz — Ücretsiz, Anlık',
      ru: 'Base64 Кодировать/Декодировать — Бесплатно',
    },
    metaDescription: {
      az: 'Mətn və faylları Base64-ə kodla, yenidən dekodla. UTF-8 dəstəyi, copy-paste, anındadır. Heç bir məlumat serverə göndərilmir.',
      en: 'Encode and decode Base64 strings and files — UTF-8 support, instant, copy-paste friendly. Nothing uploaded, nothing logged.',
      tr: 'Metin ve dosyaları Base64 olarak kodla ve çöz — UTF-8 desteği, anlık, copy-paste dostu. Hiçbir şey yüklenmez, iz bırakmaz.',
      ru: 'Кодируй и декодируй Base64 — поддержка UTF-8, файлов, мгновенно. Ничего не загружается, всё в браузере.',
    },
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions online with real-time matching. Highlight matches, view groups, and test regex patterns. Free regex tester tool.',
    shortDescription: 'Test regex patterns with live matching',
    category: 'dev',
    icon: '\uD83D\uDD0D',
    isAI: false,
    isClientSide: true,
    keywords: ['regex tester', 'regular expression', 'regex debugger', 'regex matcher'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes from text online. Free cryptographic hash generator tool.',
    shortDescription: 'Generate SHA hashes from text',
    category: 'dev',
    icon: '#\uFE0F\u20E3',
    isAI: false,
    isClientSide: true,
    keywords: ['hash generator', 'sha256', 'sha512', 'hash calculator'],
    metaTitle: {
      az: 'Hash Generatoru — SHA-1, 256, 384, 512 | Pulsuz',
      en: 'Hash Generator — SHA-1, 256, 384, 512, Free',
      tr: 'Hash Üreteci — SHA-1, 256, 384, 512 | Ücretsiz',
      ru: 'Генератор Хешей — SHA-1, 256, 384, 512 | Бесплатно',
    },
    metaDescription: {
      az: 'Mətn və ya fayllardan SHA-1, SHA-256, SHA-384, SHA-512 hash yarat. Bütün hesablama brauzerində — məlumat göndərilmir.',
      en: 'Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes from text or files. All hashing runs in your browser — nothing transmitted.',
      tr: 'Metin veya dosyalardan SHA-1, SHA-256, SHA-384, SHA-512 hash oluştur. Tüm hesaplama tarayıcıda — veri gönderilmez.',
      ru: 'Создай SHA-1, SHA-256, SHA-384, SHA-512 хеши из текста или файлов. Всё хеширование в браузере — данные не передаются.',
    },
  },
  {
    slug: 'url-encode-decode',
    name: 'URL Encode/Decode',
    description: 'Encode or decode URL strings online. Convert special characters to percent-encoding or decode percent-encoded URLs. Free URL encoder/decoder.',
    shortDescription: 'Encode and decode URL strings',
    category: 'dev',
    icon: '\uD83C\uDF10',
    isAI: false,
    isClientSide: true,
    keywords: ['url encode', 'url decode', 'percent encoding', 'urlencode'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWT) online. View header, payload, and expiration status. Free JWT decoder - no data sent to server.',
    shortDescription: 'Decode and inspect JWT tokens',
    category: 'dev',
    icon: '\uD83C\uDFAB',
    isAI: false,
    isClientSide: true,
    keywords: ['jwt decoder', 'jwt parser', 'json web token', 'token decoder'],
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write and preview Markdown in real-time. See formatted output as you type with support for headings, lists, code blocks, and more. Free online Markdown editor.',
    shortDescription: 'Write and preview Markdown in real-time',
    category: 'dev',
    icon: '\uD83D\uDCCB',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown preview', 'markdown editor', 'md preview', 'markdown to html'],
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. View current timestamp, support for seconds and milliseconds. Free timestamp tool.',
    shortDescription: 'Convert between Unix timestamps and dates',
    category: 'dev',
    icon: '\u23F0',
    isAI: false,
    isClientSide: true,
    keywords: ['timestamp converter', 'unix timestamp', 'epoch converter', 'date converter'],
  },
  {
    slug: 'css-minifier',
    name: 'CSS Minifier & Beautifier',
    description: 'Minify CSS to reduce file size or beautify minified CSS for readability. See size savings. Free online CSS minifier and formatter.',
    shortDescription: 'Minify or beautify CSS code',
    category: 'dev',
    icon: '\uD83C\uDFA8',
    isAI: false,
    isClientSide: true,
    keywords: ['css minifier', 'css beautifier', 'css formatter', 'minify css'],
  },
  {
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between Binary, Octal, Decimal, and Hexadecimal. Real-time conversion with input validation. Free number base converter.',
    shortDescription: 'Convert between number bases',
    category: 'dev',
    icon: '\uD83D\uDD22',
    isAI: false,
    isClientSide: true,
    keywords: ['number converter', 'binary', 'hexadecimal', 'octal', 'decimal'],
  },
  {
    slug: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format online. Supports custom delimiters, header rows, and quoted fields. Download or copy the JSON output.',
    shortDescription: 'Convert CSV data to JSON format',
    category: 'dev',
    icon: '\uD83D\uDCCA',
    isAI: false,
    isClientSide: true,
    keywords: ['csv to json', 'csv converter', 'json converter', 'data converter'],
  },
  {
    slug: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and understand cron expressions. See human-readable descriptions and next execution times. Quick presets for common schedules.',
    shortDescription: 'Parse cron expressions to human-readable text',
    category: 'dev',
    icon: '\u23F1\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['cron parser', 'cron expression', 'cron schedule', 'crontab'],
  },
  {
    slug: 'html-minifier',
    name: 'HTML Minifier & Beautifier',
    description: 'Minify HTML to reduce file size or beautify minified HTML for readability. Remove comments and whitespace. Free online HTML minifier and formatter.',
    shortDescription: 'Minify or beautify HTML code',
    category: 'dev',
    icon: '\uD83C\uDF10',
    isAI: false,
    isClientSide: true,
    keywords: ['html minifier', 'html beautifier', 'html formatter', 'minify html'],
    metaTitle: {
      az: 'HTML Minify & Beautify — Pulsuz, Anlıq',
      en: 'HTML Minifier & Beautifier — Free, Instant',
      tr: 'HTML Minify & Beautify — Ücretsiz, Anlık',
      ru: 'HTML Минификатор & Форматтер — Бесплатно',
    },
    metaDescription: {
      az: 'HTML-i minify et (boşluq, şərh sil) və ya minified HTML-i formatla. 70%-ə qədər ölçü qənaəti. Brauzerdə, pulsuz.',
      en: 'Minify HTML (strip whitespace, comments) or beautify minified HTML. Up to 70% size savings. Browser-based, free.',
      tr: 'HTML-i minify et (boşluk, yorum sil) veya minified HTML-i formatla. %70\'e kadar tasarruf. Tarayıcıda, ücretsiz.',
      ru: 'Минифицируй HTML (убери пробелы, комментарии) или отформатируй минифицированный HTML. До 70% экономии. В браузере.',
    },
  },
  {
    slug: 'js-minifier',
    name: 'JavaScript Minifier & Beautifier',
    description: 'Minify JavaScript to reduce file size or beautify minified JS for readability. Remove comments and whitespace. Free online JS minifier and formatter.',
    shortDescription: 'Minify or beautify JavaScript code',
    category: 'dev',
    icon: '\u26A1',
    isAI: false,
    isClientSide: true,
    keywords: ['js minifier', 'javascript minifier', 'js beautifier', 'minify javascript'],
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries online. Indent keywords, align clauses, and make your SQL readable. Free online SQL formatter tool.',
    shortDescription: 'Format and beautify SQL queries',
    category: 'dev',
    icon: '\uD83D\uDDC3\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql pretty print'],
  },
  {
    slug: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert JSON arrays to CSV format online. Supports custom delimiters and download. Free JSON to CSV converter tool.',
    shortDescription: 'Convert JSON arrays to CSV format',
    category: 'dev',
    icon: '\uD83D\uDCCA',
    isAI: false,
    isClientSide: true,
    keywords: ['json to csv', 'json converter', 'csv converter', 'convert json'],
  },
  {
    slug: 'ip-address-info',
    name: 'IP Address Info',
    description: 'View your public IP address, user agent, screen resolution, and browser information. Free online IP and device info tool.',
    shortDescription: 'View your IP and browser information',
    category: 'dev',
    icon: '\uD83C\uDF0D',
    isAI: false,
    isClientSide: true,
    keywords: ['ip address', 'my ip', 'user agent', 'browser info', 'what is my ip'],
  },
  {
    slug: 'json-to-yaml',
    name: 'JSON to YAML Converter',
    description: 'Convert JSON to YAML and YAML to JSON online. Bidirectional conversion with proper formatting and syntax. Free client-side JSON/YAML converter tool.',
    shortDescription: 'Convert between JSON and YAML formats',
    category: 'dev',
    icon: '\uD83D\uDD00',
    isAI: false,
    isClientSide: true,
    keywords: ['json to yaml', 'yaml to json', 'yaml converter', 'json converter', 'data format'],
  },
  {
    slug: 'xml-formatter',
    name: 'XML Formatter & Validator',
    description: 'Format, minify, and validate XML online. Beautify XML with custom indentation, validate tag matching, and minify for production. Free XML formatter tool.',
    shortDescription: 'Format, minify, and validate XML',
    category: 'dev',
    icon: '\uD83D\uDCF0',
    isAI: false,
    isClientSide: true,
    keywords: ['xml formatter', 'xml validator', 'xml beautifier', 'xml minifier', 'format xml'],
  },
  {
    slug: 'markdown-to-html',
    name: 'Markdown to HTML Converter',
    description: 'Convert Markdown to HTML with a live preview. Supports headings, bold, italic, links, code blocks, lists, blockquotes, and more. Free Markdown converter.',
    shortDescription: 'Convert Markdown to HTML with live preview',
    category: 'dev',
    icon: '\uD83D\uDCDD',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown to html', 'markdown converter', 'md to html', 'markdown parser', 'html generator'],
  },
  {
    slug: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Parse and convert YAML to JSON online with validation and error highlighting. Supports nested objects, arrays, comments, and inline collections. Free client-side YAML parser.',
    shortDescription: 'Parse YAML and convert to JSON format',
    category: 'dev',
    icon: '\uD83D\uDCCB',
    isAI: false,
    isClientSide: true,
    keywords: ['yaml to json', 'yaml parser', 'yaml converter', 'yaml validator', 'convert yaml'],
  },
  {
    slug: 'http-status-codes',
    name: 'HTTP Status Code Reference',
    description: 'Searchable reference of all HTTP status codes with descriptions and categories (1xx-5xx). Filter by category or search by code. Free HTTP status code lookup.',
    shortDescription: 'Searchable HTTP status code reference guide',
    category: 'dev',
    icon: '\uD83C\uDF10',
    isAI: false,
    isClientSide: true,
    keywords: ['http status codes', 'status code reference', 'http codes', 'http error codes', 'rest api codes'],
  },
  {
    slug: 'json-path-finder',
    name: 'JSON Path Finder',
    description: 'Navigate JSON structure with an interactive tree view. Click nodes to find their JSON path. Query values by path expression. Free JSON path explorer tool.',
    shortDescription: 'Navigate JSON and find paths interactively',
    category: 'dev',
    icon: '\uD83D\uDD0E',
    isAI: false,
    isClientSide: true,
    keywords: ['json path', 'json navigator', 'json tree', 'json explorer', 'jsonpath'],
  },
  {
    slug: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Unix file permissions interactively. Convert between octal (755) and symbolic (rwxr-xr-x) notation with common presets. Free chmod calculator.',
    shortDescription: 'Unix file permissions calculator (rwx to octal)',
    category: 'dev',
    icon: '\uD83D\uDD10',
    isAI: false,
    isClientSide: true,
    keywords: ['chmod calculator', 'file permissions', 'unix permissions', 'rwx', 'octal permissions'],
  },
  {
    slug: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create Markdown tables with a visual editor. Add rows and columns, set alignment, and copy the generated Markdown. Free online Markdown table maker.',
    shortDescription: 'Create Markdown tables with a visual editor',
    category: 'dev',
    icon: '\uD83D\uDCCB',
    isAI: false,
    isClientSide: true,
    keywords: ['markdown table', 'table generator', 'markdown editor', 'table maker', 'md table'],
  },
  {
    slug: 'regex-library',
    name: 'Regex Pattern Library',
    description: 'Browse and search a curated library of common regex patterns for emails, URLs, dates, numbers, and more. Test patterns against your input. Free regex reference.',
    shortDescription: 'Curated library of common regex patterns',
    category: 'dev',
    icon: '\uD83D\uDCDA',
    isAI: false,
    isClientSide: true,
    keywords: ['regex library', 'regex patterns', 'regex reference', 'regular expression', 'regex examples'],
  },
  {
    slug: 'css-flexbox-generator',
    name: 'CSS Flexbox Generator',
    description: 'Build CSS flexbox layouts visually. Adjust flex-direction, justify-content, align-items, flex-wrap, and gap with a live preview. Copy generated CSS code. Free flexbox playground.',
    shortDescription: 'Build flexbox layouts with visual editor',
    category: 'dev',
    icon: '\uD83D\uDCDA',
    isAI: false,
    isClientSide: true,
    keywords: ['css flexbox', 'flexbox generator', 'flex layout', 'css flex', 'flexbox playground'],
  },
  {
    slug: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON objects to TypeScript interfaces and types. Supports nested objects, arrays, and optional fields. Customize the root interface name. Free JSON to TS converter.',
    shortDescription: 'Convert JSON to TypeScript interfaces',
    category: 'dev',
    icon: '\uD83D\uDD37',
    isAI: false,
    isClientSide: true,
    keywords: ['json to typescript', 'json to ts', 'typescript interface', 'type generator', 'json converter'],
  },
  {
    slug: 'css-grid-generator',
    name: 'CSS Grid Generator',
    description: 'Create CSS Grid layouts visually. Configure rows, columns, gap, sizing, and alignment with a real-time preview. Copy generated CSS code. Free CSS Grid playground.',
    shortDescription: 'Create CSS Grid layouts with visual editor',
    category: 'dev',
    icon: '\u2B1C',
    isAI: false,
    isClientSide: true,
    keywords: ['css grid', 'grid generator', 'grid layout', 'css grid template', 'grid playground'],
  },
  {
    slug: 'cron-builder',
    name: 'Cron Expression Builder',
    description: 'Build cron expressions visually with dropdowns and presets. Get human-readable descriptions and parse existing expressions. Free online cron builder tool.',
    shortDescription: 'Visual cron expression editor with presets',
    category: 'dev',
    icon: '\u23F0',
    isAI: false,
    isClientSide: true,
    keywords: ['cron builder', 'cron generator', 'cron expression', 'cron editor', 'crontab builder'],
  },
  {
    slug: 'git-command-generator',
    name: 'Git Command Generator',
    description: 'Generate git commands by selecting operations and filling in parameters. Browse by category: branch, commit, remote, stash, and more. Free git command reference.',
    shortDescription: 'Generate git commands with a visual builder',
    category: 'dev',
    icon: '\uD83D\uDD00',
    isAI: false,
    isClientSide: true,
    keywords: ['git command', 'git generator', 'git reference', 'git cheatsheet', 'git helper'],
  },
  {
    slug: 'http-header-parser',
    name: 'HTTP Header Parser',
    description: 'Parse and categorize HTTP headers. Identify content, caching, security, CORS, and authentication headers with color-coded categories. Free HTTP header analyzer.',
    shortDescription: 'Parse and categorize HTTP headers',
    category: 'dev',
    icon: '\uD83D\uDCE8',
    isAI: false,
    isClientSide: true,
    keywords: ['http header', 'header parser', 'http analyzer', 'response headers', 'request headers'],
  },
  {
    slug: 'sql-to-mongodb',
    name: 'SQL to MongoDB Converter',
    description: 'Convert SQL queries to MongoDB commands. Supports SELECT, INSERT, UPDATE, DELETE with WHERE clauses. Free SQL to MongoDB query translator.',
    shortDescription: 'Convert SQL queries to MongoDB commands',
    category: 'dev',
    icon: '\uD83D\uDDC4\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['sql to mongodb', 'mongodb converter', 'sql converter', 'nosql', 'query converter'],
  },
  {
    slug: 'api-response-formatter',
    name: 'API Response Formatter',
    description: 'Format and inspect API JSON responses with tree view, formatted view, and minified output. View response statistics and navigate nested data. Free API response tool.',
    shortDescription: 'Format and inspect API JSON responses',
    category: 'dev',
    icon: '\uD83D\uDCE1',
    isAI: false,
    isClientSide: true,
    keywords: ['api formatter', 'json viewer', 'response formatter', 'api inspector', 'json tree'],
  },
]
