import { Tool } from '@/types/tool'

export const generatorTools: Tool[] = [
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and more. Download as PNG or SVG. Free online QR code maker with customizable size and colors.',
    shortDescription: 'Generate QR codes for any text or URL',
    category: 'generators',
    icon: '\uD83D\uDCF1',
    isAI: false,
    isClientSide: true,
    keywords: ['qr code', 'qr generator', 'barcode', 'qr maker'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker & Palette Generator',
    description: 'Pick colors, convert between HEX, RGB, HSL formats, and generate beautiful color palettes. Free online color picker tool for designers.',
    shortDescription: 'Pick colors and generate palettes',
    category: 'generators',
    icon: '\uD83C\uDFA8',
    isAI: false,
    isClientSide: true,
    keywords: ['color picker', 'color palette', 'hex to rgb', 'color converter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate lorem ipsum placeholder text for your designs and mockups. Choose paragraphs, sentences, or words. Free dummy text generator.',
    shortDescription: 'Generate placeholder text',
    category: 'generators',
    icon: '\uD83D\uDCC4',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with customizable length and character types. Password strength indicator included. Secure client-side generation.',
    shortDescription: 'Generate secure random passwords',
    category: 'generators',
    icon: '\uD83D\uDD12',
    isAI: false,
    isClientSide: true,
    keywords: ['password generator', 'random password', 'secure password', 'strong password'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 identifiers online. Bulk generation, uppercase/lowercase options, with or without hyphens. Free UUID generator tool.',
    shortDescription: 'Generate UUID v4 identifiers',
    category: 'generators',
    icon: '\uD83C\uDD94',
    isAI: false,
    isClientSide: true,
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'unique id'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO. Create Open Graph, Twitter Card, and standard meta tags with a live Google preview. Free meta tag generator.',
    shortDescription: 'Generate SEO meta tags for your website',
    category: 'generators',
    icon: '\uD83C\uDFF7\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['meta tag generator', 'seo tags', 'open graph', 'twitter card'],
  },
  {
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and convert aspect ratios. Lock ratios, use common presets like 16:9 and 4:3, and find matching resolutions. Free aspect ratio tool.',
    shortDescription: 'Calculate and convert aspect ratios',
    category: 'generators',
    icon: '\uD83D\uDCD0',
    isAI: false,
    isClientSide: true,
    keywords: ['aspect ratio', 'ratio calculator', 'screen ratio', 'resolution calculator'],
  },
  {
    slug: 'emoji-picker',
    name: 'Emoji Picker & Search',
    description: 'Browse, search, and copy emojis by category. Click any emoji to copy it to your clipboard instantly. Free online emoji picker.',
    shortDescription: 'Browse and copy emojis by category',
    category: 'generators',
    icon: '\uD83D\uDE00',
    isAI: false,
    isClientSide: true,
    keywords: ['emoji picker', 'emoji search', 'copy emoji', 'emoji keyboard'],
  },
  {
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful linear and radial CSS gradients with multiple color stops. Preview in real-time and copy the CSS code. Free gradient generator.',
    shortDescription: 'Create CSS gradients with color stops',
    category: 'generators',
    icon: '\uD83C\uDF08',
    isAI: false,
    isClientSide: true,
    keywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient'],
  },
  {
    slug: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images with custom dimensions, colors, and text. Download as PNG or JPEG. Free online placeholder image maker.',
    shortDescription: 'Generate placeholder images with custom size',
    category: 'generators',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['placeholder image', 'dummy image', 'placeholder generator', 'test image'],
  },
  {
    slug: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Upload an image and generate favicons in multiple sizes (16x16 to 512x512). Download individually or as a ZIP. Free client-side favicon generator.',
    shortDescription: 'Generate multi-size favicons from an image',
    category: 'generators',
    icon: '\u2B50',
    isAI: false,
    isClientSide: true,
    keywords: ['favicon generator', 'favicon maker', 'ico generator', 'website icon', 'app icon'],
  },
  {
    slug: 'svg-to-png',
    name: 'SVG to PNG Converter',
    description: 'Convert SVG to PNG with custom dimensions online. Paste SVG code or upload a file, set width and height, and download as PNG. Free client-side converter.',
    shortDescription: 'Convert SVG to PNG with custom dimensions',
    category: 'generators',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['svg to png', 'svg converter', 'svg to image', 'convert svg', 'png generator'],
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units of length, weight, temperature, speed, digital storage, time, and area. Supports metric and imperial units with instant conversion. Free online unit converter.',
    shortDescription: 'Convert between measurement units',
    category: 'generators',
    icon: '\uD83D\uDCCF',
    isAI: false,
    isClientSide: true,
    keywords: ['unit converter', 'measurement converter', 'metric converter', 'imperial converter', 'length converter'],
  },
  {
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices with company details, line items, tax calculation, and totals. Preview and download as PDF using browser print. Free online invoice maker.',
    shortDescription: 'Create and download professional invoices',
    category: 'generators',
    icon: '\uD83E\uDDFE',
    isAI: false,
    isClientSide: true,
    keywords: ['invoice generator', 'invoice maker', 'invoice creator', 'billing', 'invoice pdf'],
  },
  {
    slug: 'market-tracker',
    name: 'Market Price Tracker',
    description: 'Track live prices of Bitcoin, Ethereum, Gold, and Oil. See 24-hour price changes, convert between currencies (USD, AZN, EUR), and view market summaries. Free real-time market tracker.',
    shortDescription: 'Live crypto, gold & oil price tracker',
    category: 'generators',
    icon: '\uD83D\uDCC8',
    isAI: false,
    isClientSide: false,
    keywords: ['market tracker', 'bitcoin price', 'crypto prices', 'gold price', 'oil price', 'market prices', 'price tracker'],
  },
  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Extract animated clips from video files using browser APIs. Set start time, duration, FPS, and resolution. Free client-side video to animation converter.',
    shortDescription: 'Extract animated clips from video files',
    category: 'generators',
    icon: '\uD83C\uDFAC',
    isAI: false,
    isClientSide: true,
    keywords: ['video to gif', 'gif maker', 'video converter', 'animated gif', 'video clip'],
  },
  {
    slug: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a base color. Supports complementary, analogous, triadic, tetradic, split-complementary, and monochromatic harmonies. Export as CSS variables.',
    shortDescription: 'Generate harmonious color palettes',
    category: 'generators',
    icon: '\uD83C\uDFA8',
    isAI: false,
    isClientSide: true,
    keywords: ['color palette', 'color scheme', 'color harmony', 'complementary colors', 'color generator'],
  },
  {
    slug: 'backlink-generator',
    name: 'Backlink Generator',
    description: 'Generate backlinks in multiple formats: HTML, Markdown, BBCode, Textile, Wiki, and reStructuredText. Configure rel attributes, target, and anchor text. Free link code generator.',
    shortDescription: 'Generate links in HTML, Markdown, BBCode, and more',
    category: 'generators',
    icon: '\uD83D\uDD17',
    isAI: false,
    isClientSide: true,
    keywords: ['backlink generator', 'link generator', 'html link', 'markdown link', 'bbcode link'],
  },
]
