import { Tool } from '@/types/tool'

export const generatorTools: Tool[] = [
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and more. Download as PNG or SVG. Free online QR code maker with customizable size and colors.',
    shortDescription: 'Generate QR codes for any text or URL',
    category: 'generators',
    icon: '\uD83D\uDCF1',
    isAI: false,
    isClientSide: true,
    keywords: ['qr code', 'qr generator', 'barcode', 'qr maker'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker & Palette Generator',
    description: 'Pick colors, convert between HEX, RGB, HSL formats, and generate beautiful color palettes. Free online color picker tool for designers.',
    shortDescription: 'Pick colors and generate palettes',
    category: 'generators',
    icon: '\uD83C\uDFA8',
    isAI: false,
    isClientSide: true,
    keywords: ['color picker', 'color palette', 'hex to rgb', 'color converter'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate lorem ipsum placeholder text for your designs and mockups. Choose paragraphs, sentences, or words. Free dummy text generator.',
    shortDescription: 'Generate placeholder text',
    category: 'generators',
    icon: '\uD83D\uDCC4',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with customizable length and character types. Password strength indicator included. Secure client-side generation.',
    shortDescription: 'Generate secure random passwords',
    category: 'generators',
    icon: '\uD83D\uDD12',
    isAI: false,
    isClientSide: true,
    keywords: ['password generator', 'random password', 'secure password', 'strong password'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 identifiers online. Bulk generation, uppercase/lowercase options, with or without hyphens. Free UUID generator tool.',
    shortDescription: 'Generate UUID v4 identifiers',
    category: 'generators',
    icon: '\uD83C\uDD94',
    isAI: false,
    isClientSide: true,
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'unique id'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO. Create Open Graph, Twitter Card, and standard meta tags with a live Google preview. Free meta tag generator.',
    shortDescription: 'Generate SEO meta tags for your website',
    category: 'generators',
    icon: '\uD83C\uDFF7\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['meta tag generator', 'seo tags', 'open graph', 'twitter card'],
  },
  {
    slug: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and convert aspect ratios. Lock ratios, use common presets like 16:9 and 4:3, and find matching resolutions. Free aspect ratio tool.',
    shortDescription: 'Calculate and convert aspect ratios',
    category: 'generators',
    icon: '\uD83D\uDCD0',
    isAI: false,
    isClientSide: true,
    keywords: ['aspect ratio', 'ratio calculator', 'screen ratio', 'resolution calculator'],
  },
  {
    slug: 'emoji-picker',
    name: 'Emoji Picker & Search',
    description: 'Browse, search, and copy emojis by category. Click any emoji to copy it to your clipboard instantly. Free online emoji picker.',
    shortDescription: 'Browse and copy emojis by category',
    category: 'generators',
    icon: '\uD83D\uDE00',
    isAI: false,
    isClientSide: true,
    keywords: ['emoji picker', 'emoji search', 'copy emoji', 'emoji keyboard'],
  },
  {
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful linear and radial CSS gradients with multiple color stops. Preview in real-time and copy the CSS code. Free gradient generator.',
    shortDescription: 'Create CSS gradients with color stops',
    category: 'generators',
    icon: '\uD83C\uDF08',
    isAI: false,
    isClientSide: true,
    keywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient'],
  },
  {
    slug: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images with custom dimensions, colors, and text. Download as PNG or JPEG. Free online placeholder image maker.',
    shortDescription: 'Generate placeholder images with custom size',
    category: 'generators',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['placeholder image', 'dummy image', 'placeholder generator', 'test image'],
  },
  {
    slug: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Upload an image and generate favicons in multiple sizes (16x16 to 512x512). Download individually or as a ZIP. Free client-side favicon generator.',
    shortDescription: 'Generate multi-size favicons from an image',
    category: 'generators',
    icon: '\u2B50',
    isAI: false,
    isClientSide: true,
    keywords: ['favicon generator', 'favicon maker', 'ico generator', 'website icon', 'app icon'],
  },
  {
    slug: 'svg-to-png',
    name: 'SVG to PNG Converter',
    description: 'Convert SVG to PNG with custom dimensions online. Paste SVG code or upload a file, set width and height, and download as PNG. Free client-side converter.',
    shortDescription: 'Convert SVG to PNG with custom dimensions',
    category: 'generators',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['svg to png', 'svg converter', 'svg to image', 'convert svg', 'png generator'],
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units of length, weight, temperature, speed, digital storage, time, and area. Supports metric and imperial units with instant conversion. Free online unit converter.',
    shortDescription: 'Convert between measurement units',
    category: 'generators',
    icon: '\uD83D\uDCCF',
    isAI: false,
    isClientSide: true,
    keywords: ['unit converter', 'measurement converter', 'metric converter', 'imperial converter', 'length converter'],
  },
  {
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices with company details, line items, tax calculation, and totals. Preview and download as PDF using browser print. Free online invoice maker.',
    shortDescription: 'Create and download professional invoices',
    category: 'generators',
    icon: '\uD83E\uDDFE',
    isAI: false,
    isClientSide: true,
    keywords: ['invoice generator', 'invoice maker', 'invoice creator', 'billing', 'invoice pdf'],
  },
  {
    slug: 'market-tracker',
    name: 'Market Price Tracker',
    description: 'Track live prices of Bitcoin, Ethereum, Gold, and Oil. See 24-hour price changes, convert between currencies (USD, AZN, EUR), and view market summaries. Free real-time market tracker.',
    shortDescription: 'Live crypto, gold & oil price tracker',
    category: 'generators',
    icon: '\uD83D\uDCC8',
    isAI: false,
    isClientSide: false,
    keywords: ['market tracker', 'bitcoin price', 'crypto prices', 'gold price', 'oil price', 'market prices', 'price tracker'],
  },
  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Extract animated clips from video files using browser APIs. Set start time, duration, FPS, and resolution. Free client-side video to animation converter.',
    shortDescription: 'Extract animated clips from video files',
    category: 'generators',
    icon: '\uD83C\uDFAC',
    isAI: false,
    isClientSide: true,
    keywords: ['video to gif', 'gif maker', 'video converter', 'animated gif', 'video clip'],
  },
  {
    slug: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a base color. Supports complementary, analogous, triadic, tetradic, split-complementary, and monochromatic harmonies. Export as CSS variables.',
    shortDescription: 'Generate harmonious color palettes',
    category: 'generators',
    icon: '\uD83C\uDFA8',
    isAI: false,
    isClientSide: true,
    keywords: ['color palette', 'color scheme', 'color harmony', 'complementary colors', 'color generator'],
  },
  {
    slug: 'backlink-generator',
    name: 'Backlink Generator',
    description: 'Generate backlinks in multiple formats: HTML, Markdown, BBCode, Textile, Wiki, and reStructuredText. Configure rel attributes, target, and anchor text. Free link code generator.',
    shortDescription: 'Generate links in HTML, Markdown, BBCode, and more',
    category: 'generators',
    icon: '\uD83D\uDD17',
    isAI: false,
    isClientSide: true,
    keywords: ['backlink generator', 'link generator', 'html link', 'markdown link', 'bbcode link'],
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days from your date of birth. See total days, weeks, months lived and days until next birthday. Free online age calculator.',
    shortDescription: 'Calculate exact age from date of birth',
    category: 'generators',
    icon: '\uD83C\uDF82',
    isAI: false,
    isClientSide: true,
    keywords: ['age calculator', 'birthday calculator', 'how old am i', 'date of birth calculator', 'age finder'],
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index (BMI) using height and weight. Supports metric and imperial units. Shows BMI category, scale visualization, and healthy weight range. Free BMI calculator.',
    shortDescription: 'Calculate BMI from height and weight',
    category: 'generators',
    icon: '\u2696\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['bmi calculator', 'body mass index', 'weight calculator', 'health calculator', 'bmi checker'],
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages with 3 modes: find X% of Y, find what percent X is of Y, and calculate percentage change between two values. Free online percentage calculator.',
    shortDescription: 'Calculate percentages in multiple modes',
    category: 'generators',
    icon: '%',
    isAI: false,
    isClientSide: true,
    keywords: ['percentage calculator', 'percent calculator', 'percentage change', 'percent of', 'calculate percentage'],
  },
  {
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate CODE128 and CODE39 barcodes from text or numbers. Customize bar width, height, and text display. Download as PNG. Free client-side barcode generator.',
    shortDescription: 'Generate barcodes from text or numbers',
    category: 'generators',
    icon: '\uD83D\uDCE6',
    isAI: false,
    isClientSide: true,
    keywords: ['barcode generator', 'barcode maker', 'code128', 'code39', 'barcode creator'],
  },
  {
    slug: 'css-box-shadow-generator',
    name: 'CSS Box Shadow Generator',
    description: 'Create CSS box-shadow visually. Adjust offset, blur, spread, color, and opacity. Multiple layers and inset shadows supported. Free box shadow generator.',
    shortDescription: 'Generate CSS box-shadow with visual controls',
    category: 'generators',
    icon: '\uD83D\uDDA5\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['box shadow generator', 'css shadow', 'drop shadow', 'css box shadow', 'shadow generator'],
  },
  {
    slug: 'loan-calculator',
    name: 'Loan/EMI Calculator',
    description: 'Calculate monthly loan payments, total interest, and view a full amortization schedule. Supports custom loan amount, interest rate, and term in months or years. Free online EMI calculator.',
    shortDescription: 'Calculate loan payments and amortization',
    category: 'generators',
    icon: '\uD83C\uDFE6',
    isAI: false,
    isClientSide: true,
    keywords: ['loan calculator', 'emi calculator', 'mortgage calculator', 'interest calculator', 'amortization'],
  },
  {
    slug: 'robots-txt-generator',
    name: 'robots.txt Generator',
    description: 'Generate robots.txt files with visual editor. Configure user-agent rules, disallow paths, sitemap URL, and crawl delay. Free online robots.txt builder.',
    shortDescription: 'Generate robots.txt with visual editor',
    category: 'generators',
    icon: '\uD83E\uDD16',
    isAI: false,
    isClientSide: true,
    keywords: ['robots.txt', 'robots txt generator', 'seo', 'crawler', 'search engine'],
  },
  {
    slug: 'htaccess-generator',
    name: '.htaccess Generator',
    description: 'Generate .htaccess files with HTTPS redirect, www redirect, gzip compression, browser caching, custom error pages, and URL redirects. Free .htaccess builder.',
    shortDescription: 'Generate .htaccess redirect and rewrite rules',
    category: 'generators',
    icon: '\u2699\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['htaccess', 'htaccess generator', 'redirect', 'rewrite', 'apache'],
  },
  {
    slug: 'privacy-policy-generator',
    name: 'Privacy Policy Generator',
    description: 'Generate a privacy policy for your website. Customize for cookies, analytics, user accounts, payments, and newsletters. Free privacy policy template generator.',
    shortDescription: 'Generate a privacy policy for your website',
    category: 'generators',
    icon: '\uD83D\uDD12',
    isAI: false,
    isClientSide: true,
    keywords: ['privacy policy', 'privacy policy generator', 'gdpr', 'legal', 'website policy'],
  },
  {
    slug: 'terms-of-service-generator',
    name: 'Terms of Service Generator',
    description: 'Generate terms of service for your website. Include sections for user accounts, payments, user content, IP, and termination. Free ToS template generator.',
    shortDescription: 'Generate terms of service for your website',
    category: 'generators',
    icon: '\uD83D\uDCDC',
    isAI: false,
    isClientSide: true,
    keywords: ['terms of service', 'tos generator', 'legal', 'terms and conditions', 'website terms'],
  },
  {
    slug: 'sitemap-generator',
    name: 'XML Sitemap Generator',
    description: 'Create XML sitemaps from a list of URLs. Set change frequency, priority, and last modified date for each URL. Bulk add support. Free sitemap generator.',
    shortDescription: 'Create XML sitemaps from URL lists',
    category: 'generators',
    icon: '\uD83D\uDDFA\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['sitemap generator', 'xml sitemap', 'seo sitemap', 'sitemap builder', 'sitemap creator'],
  },
  {
    slug: 'open-graph-generator',
    name: 'Open Graph Tag Generator',
    description: 'Generate Open Graph and Twitter Card meta tags for social media sharing. Preview how your page will look when shared. Free OG tag generator.',
    shortDescription: 'Generate OG and Twitter Card meta tags',
    category: 'generators',
    icon: '\uD83D\uDD17',
    isAI: false,
    isClientSide: true,
    keywords: ['open graph', 'og tags', 'twitter card', 'social media tags', 'meta tags'],
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between 20+ world currencies with offline approximate rates. Supports USD, EUR, GBP, AZN, TRY, RUB, JPY, and more. Free currency converter tool.',
    shortDescription: 'Convert between world currencies',
    category: 'generators',
    icon: '\uD83D\uDCB1',
    isAI: false,
    isClientSide: true,
    keywords: ['currency converter', 'exchange rate', 'money converter', 'forex', 'currency calculator'],
  },
  {
    slug: 'tax-calculator',
    name: 'Tax Calculator',
    description: 'Calculate tax amounts with tax-exclusive and tax-inclusive modes. Quick rate presets for common tax rates worldwide. Free online tax calculator.',
    shortDescription: 'Calculate tax amounts and totals',
    category: 'generators',
    icon: '\uD83D\uDCB0',
    isAI: false,
    isClientSide: true,
    keywords: ['tax calculator', 'vat calculator', 'sales tax', 'tax rate', 'tax calculation'],
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate restaurant tips with preset percentages. Split the bill between multiple people. Compare tip amounts across different rates. Free tip calculator.',
    shortDescription: 'Calculate tips and split bills',
    category: 'generators',
    icon: '\uD83C\uDF7D\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['tip calculator', 'restaurant tip', 'bill split', 'gratuity', 'tip percentage'],
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest with monthly contributions. View year-by-year breakdown, interest vs principal ratio, and total growth. Free compound interest tool.',
    shortDescription: 'Calculate compound interest with contributions',
    category: 'generators',
    icon: '\uD83D\uDCC8',
    isAI: false,
    isClientSide: true,
    keywords: ['compound interest', 'interest calculator', 'investment calculator', 'savings calculator', 'compound growth'],
  },
  {
    slug: 'youtube-thumbnail-text',
    name: 'YouTube Thumbnail Text',
    description: 'Create YouTube thumbnail text overlays with custom fonts, colors, backgrounds, and outlines. Download as 1280x720 PNG. Free thumbnail text generator.',
    shortDescription: 'Create text overlays for YouTube thumbnails',
    category: 'generators',
    icon: '\u25B6\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['youtube thumbnail', 'thumbnail maker', 'thumbnail text', 'youtube banner', 'video thumbnail'],
  },
  {
    slug: 'meme-generator',
    name: 'Meme Generator — Free Online Meme Maker',
    description: 'Create memes with popular templates or your own images. Add top and bottom text, customize font size and color. Download as PNG. Free client-side meme generator.',
    shortDescription: 'Create memes with templates or custom images',
    category: 'generators',
    icon: '\uD83D\uDE02',
    isAI: false,
    isClientSide: true,
    keywords: ['meme generator', 'meme maker', 'meme creator', 'create meme', 'meme template'],
  },
  {
    slug: 'time-calculator',
    name: 'Time & Date Calculator — Difference, Countdown, Timezone',
    description: 'Calculate date differences, add or subtract time from dates, countdown to events, and convert between timezones. Free online time and date calculator.',
    shortDescription: 'Calculate date differences, countdown & timezone',
    category: 'generators',
    icon: '\u23F0',
    isAI: false,
    isClientSide: true,
    keywords: ['time calculator', 'date calculator', 'date difference', 'countdown timer', 'timezone converter', 'days between dates'],
  },
]
