import { Tool } from '@/types/tool'

export const imageTools: Tool[] = [
  {
    slug: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress and resize images online. Reduce file size while maintaining quality. Supports JPEG, PNG, and WebP. Free client-side image compression.',
    shortDescription: 'Compress images to reduce file size',
    category: 'image',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['image compress', 'image resize', 'reduce image size', 'image optimizer'],
    metaDescription: {
      az: 'Şəkil sıxma — JPEG, PNG və WebP formatlarında fayl ölçüsünü 70%-ə qədər azalt, keyfiyyəti qoru. Heç nə yüklənmir.',
      en: 'Image compressor — shrink JPEG, PNG, and WebP files up to 70% with minimal quality loss. No upload, no tracking, private.',
      tr: 'Görüntü sıkıştırma — JPEG, PNG ve WebP dosyalarını %70\'e kadar küçült, kaliteyi koru. Yükleme yok, iz bırakmaz.',
      ru: 'Сжатие изображений — уменьши JPEG, PNG и WebP файлы до 70% с минимальной потерей качества. Без загрузки, анонимно.',
    },
  },
  {
    slug: 'image-convert',
    name: 'Image Converter',
    description: 'Convert images between JPEG, PNG, and WebP formats online. Free client-side image converter - your files stay in your browser.',
    shortDescription: 'Convert images between formats',
    category: 'image',
    icon: '\uD83D\uDD04',
    isAI: false,
    isClientSide: true,
    keywords: ['image converter', 'png to jpg', 'jpg to png', 'webp converter'],
    metaDescription: {
      az: 'Şəkil çevirici — JPEG, PNG, WebP və HEIC arasında konvertasiya. Heç nə yüklənmir, metadata silinir, hər şey brauzerində.',
      en: 'Image converter — JPEG, PNG, WebP, and HEIC conversions. Nothing uploaded, metadata stripped, everything runs in your browser.',
      tr: 'Görüntü dönüştürücü — JPEG, PNG, WebP ve HEIC dönüşümleri. Hiçbir şey yüklenmez, metaveri silinir, her şey tarayıcında.',
      ru: 'Конвертер изображений — JPEG, PNG, WebP и HEIC. Ничего не загружается, метаданные удаляются, всё в браузере.',
    },
  },
  {
    slug: 'image-resize',
    name: 'Image Resizer',
    description: 'Resize images to exact dimensions or by percentage online. Maintain aspect ratio, supports JPEG, PNG, and WebP. Free client-side image resizer.',
    shortDescription: 'Resize images to exact dimensions',
    category: 'image',
    icon: '\uD83D\uDCD0',
    isAI: false,
    isClientSide: true,
    keywords: ['image resize', 'resize image', 'image dimensions', 'scale image'],
  },
  {
    slug: 'image-crop',
    name: 'Image Cropper',
    description: 'Crop images with a drag-to-select area online. Select any region of your image and download the cropped result. Free client-side image cropper.',
    shortDescription: 'Crop images with drag-to-select',
    category: 'image',
    icon: '\u2702\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['image crop', 'crop image', 'image cropper', 'cut image'],
  },
  {
    slug: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings. Output as Data URI, raw Base64, CSS background, or HTML img tag. Supports JPEG, PNG, GIF, WebP, SVG. Free client-side converter.',
    shortDescription: 'Convert images to Base64 strings',
    category: 'image',
    icon: '\uD83D\uDD23',
    isAI: false,
    isClientSide: true,
    keywords: ['image to base64', 'base64 image', 'data uri', 'image encoder', 'base64 converter'],
  },
  {
    slug: 'background-remover',
    name: 'Image Background Remover — Free Online, AI-Powered',
    description: 'Remove image backgrounds instantly using AI. Upload any photo and get a transparent PNG. Free client-side background remover - your files never leave your browser.',
    shortDescription: 'Remove image backgrounds with AI',
    category: 'image',
    icon: '\u2728',
    isAI: false,
    isClientSide: true,
    keywords: ['background remover', 'remove background', 'transparent background', 'image background', 'png transparent'],
  },
  {
    slug: 'base64-to-image',
    name: 'Base64 to Image',
    description: 'Decode Base64 strings back to images. Auto-detects JPEG, PNG, GIF, WebP, and SVG formats. Preview and download the decoded image. Free client-side decoder.',
    shortDescription: 'Decode Base64 strings to images',
    category: 'image',
    icon: '\uD83D\uDDBC\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['base64 to image', 'decode base64', 'image decoder', 'data uri to image', 'base64 viewer'],
  },
]
