import { Tool } from '@/types/tool'

export const pdfTools: Tool[] = [
  {
    slug: 'pdf-merge',
    name: 'Merge PDF Files Online Free — No Upload, 100% Private',
    description: 'Merge multiple PDF files into one document online. Rearrange pages, combine PDFs in any order. Free client-side PDF merger - your files never leave your browser.',
    shortDescription: 'Combine multiple PDFs into one',
    category: 'pdf',
    icon: '\uD83D\uDCD1',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf merge', 'combine pdf', 'join pdf', 'pdf combiner'],
    metaTitle: {
      az: 'PDF Birləşdirmə — Pulsuz, Yüklənmədən',
      en: 'Merge PDF Files Online — No Upload, No Watermark',
      tr: 'PDF Birleştirme — Ücretsiz, Filigransız, Yüklemesiz',
      ru: 'Объединить PDF Онлайн — Бесплатно, Без Загрузки',
    },
    metaDescription: {
      az: 'PDF faylları brauzerində birləşdir — sürüklə-at, səhifələri sırala, tək sənəd al. Heç bir fayl serverə göndərilmir.',
      en: 'Merge PDF files in your browser — drag, drop, reorder, download. Files never leave your device. Free, no signup, no watermark.',
      tr: 'PDF dosyalarını tarayıcında birleştir — sürükle-bırak, sırala, indir. Dosyaların cihazından çıkmaz. Ücretsiz, filigransız.',
      ru: 'Объедини PDF-файлы прямо в браузере — перетащи, сортируй, скачай. Файлы не покидают устройство. Бесплатно, без водяного знака.',
    },
  },
  {
    slug: 'pdf-split',
    name: 'PDF Page Splitter',
    description: 'Extract specific pages from a PDF file online. Select page ranges to split and download. Free client-side PDF splitter - your files never leave your browser.',
    shortDescription: 'Extract specific pages from a PDF',
    category: 'pdf',
    icon: '\u2702\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf split', 'pdf extract pages', 'pdf page splitter', 'split pdf'],
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word Converter — Free Online, No Upload',
    description: 'Convert PDF files to editable Word documents (.docx) online. Extract text from PDF and download as Word file. Free client-side converter - your files never leave your browser.',
    shortDescription: 'Convert PDF to editable Word document',
    category: 'pdf',
    icon: '\uD83D\uDCDD',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf to word', 'pdf to docx', 'pdf converter', 'convert pdf to word', 'pdf to word converter'],
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF Converter — Free Online, No Upload',
    description: 'Convert Word documents (.docx) to PDF online. Preview your document and save as PDF using browser print. Free client-side converter - your files never leave your browser.',
    shortDescription: 'Convert Word documents to PDF',
    category: 'pdf',
    icon: '\uD83D\uDCC4',
    isAI: false,
    isClientSide: true,
    keywords: ['word to pdf', 'docx to pdf', 'word converter', 'convert word to pdf', 'word to pdf converter'],
  },
  {
    slug: 'pdf-compress',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size online. Remove metadata and optimize structure to compress PDFs. Free client-side PDF compressor - your files never leave your browser.',
    shortDescription: 'Reduce PDF file size',
    category: 'pdf',
    icon: '\uD83D\uDCE6',
    isAI: false,
    isClientSide: true,
    keywords: ['pdf compress', 'reduce pdf size', 'pdf compressor', 'shrink pdf'],
    metaTitle: {
      az: 'PDF Sıxma — Ölçünü 70%-ə Qədər Azalt, Pulsuz',
      en: 'PDF Compressor — Shrink Up To 70%, No Upload',
      tr: 'PDF Sıkıştırma — %70\'e Kadar Küçült, Yüklemesiz',
      ru: 'Сжатие PDF Бесплатно — Уменьши до 70%, Без Загрузки',
    },
    metaDescription: {
      az: 'PDF-nin ölçüsünü 70%-ə qədər azalt — keyfiyyət saxlanılır, metadata silinir. Email və mesajlaşma üçün ideal. Brauzerdə, pulsuz.',
      en: 'Shrink PDFs up to 70% smaller — quality preserved, metadata stripped. Perfect for email and messaging. Browser-only, free, private.',
      tr: 'PDF boyutunu %70\'e kadar küçült — kalite korunur, meta veri silinir. E-posta ve mesajlaşma için ideal. Tarayıcıda, ücretsiz.',
      ru: 'Сожми PDF до 70% меньше — качество сохраняется, метаданные удаляются. Идеально для email и мессенджеров. В браузере, бесплатно.',
    },
  },
]
