import { Tool } from '@/types/tool'

export const textTools: Tool[] = [
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Estimate reading time. Free online word counter tool for writers and students.',
    shortDescription: 'Count words, characters, and more',
    category: 'text',
    icon: '\uD83D\uDD22',
    isAI: false,
    isClientSide: true,
    keywords: ['word counter', 'character counter', 'text counter', 'word count'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case and more. Free online text case converter.',
    shortDescription: 'Convert text between different cases',
    category: 'text',
    icon: 'Aa',
    isAI: false,
    isClientSide: true,
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake case'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate clean URL slugs from any text. Remove special characters, handle accents, and create SEO-friendly URLs. Free online slug generator.',
    shortDescription: 'Generate URL-friendly slugs from text',
    category: 'text',
    icon: '\uD83D\uDD17',
    isAI: false,
    isClientSide: true,
    keywords: ['slug generator', 'url slug', 'permalink', 'seo url'],
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and find differences. Highlight additions, deletions, and changes line by line. Free online text comparison tool.',
    shortDescription: 'Compare two texts and find differences',
    category: 'text',
    icon: '\uD83D\uDCCA',
    isAI: false,
    isClientSide: true,
    keywords: ['text diff', 'text compare', 'diff checker', 'find differences'],
  },
  {
    slug: 'html-entity-codec',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode special characters to HTML entities or decode HTML entities back to text. Supports named and numeric entities. Free online tool.',
    shortDescription: 'Encode and decode HTML entities',
    category: 'text',
    icon: '&lt;',
    isAI: false,
    isClientSide: true,
    keywords: ['html entity', 'html encode', 'html decode', 'special characters'],
  },
  {
    slug: 'text-to-binary',
    name: 'Text to Binary Converter',
    description: 'Convert text to binary, hexadecimal, or octal and vice versa. Free online text to binary converter with multiple encoding formats.',
    shortDescription: 'Convert text to binary, hex, or octal',
    category: 'text',
    icon: '\uD83D\uDCBB',
    isAI: false,
    isClientSide: true,
    keywords: ['text to binary', 'binary converter', 'hex converter', 'octal converter'],
  },
  {
    slug: 'rot13-encoder',
    name: 'ROT13 Encoder/Decoder',
    description: 'Encode and decode text using ROT13 Caesar cipher. Supports custom shift values from 1 to 25. Free online ROT13 encoder tool.',
    shortDescription: 'ROT13 and Caesar cipher encoder/decoder',
    category: 'text',
    icon: '\uD83D\uDD04',
    isAI: false,
    isClientSide: true,
    keywords: ['rot13', 'caesar cipher', 'rot13 encoder', 'cipher decoder'],
  },
  {
    slug: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Focus timer using the Pomodoro Technique. 25-minute work sessions with 5-minute breaks. Sound notifications and session tracking. Free online timer.',
    shortDescription: '25/5 minute work/break focus timer',
    category: 'text',
    icon: '\u23F1\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['pomodoro timer', 'focus timer', 'work timer', 'productivity timer'],
  },
  {
    slug: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to speech using the Web Speech API. Choose from available voices, adjust speed, pitch, and volume. Free online text-to-speech reader.',
    shortDescription: 'Read text aloud with voice controls',
    category: 'text',
    icon: '\uD83D\uDD0A',
    isAI: false,
    isClientSide: true,
    keywords: ['text to speech', 'tts', 'read aloud', 'speech synthesis', 'voice reader'],
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, words, sentences, paragraphs, and lines. View reading time, speaking time, character frequency, and more. Free detailed text analysis tool.',
    shortDescription: 'Detailed character and text statistics',
    category: 'text',
    icon: '\uD83D\uDD24',
    isAI: false,
    isClientSide: true,
    keywords: ['character counter', 'letter counter', 'text statistics', 'reading time', 'speaking time'],
  },
  {
    slug: 'find-and-replace',
    name: 'Find and Replace',
    description: 'Find and replace text with regex support, case sensitivity, and whole word matching. Highlights all matches in real-time. Free online find and replace tool.',
    shortDescription: 'Find and replace text with regex support',
    category: 'text',
    icon: '\uD83D\uDD0D',
    isAI: false,
    isClientSide: true,
    keywords: ['find and replace', 'search replace', 'text replace', 'regex replace', 'find text'],
  },
  {
    slug: 'morse-code',
    name: 'Morse Code Translator',
    description: 'Convert text to Morse code and Morse code to text. Includes audio playback using Web Audio API, reference chart, and bidirectional translation. Free online Morse code translator.',
    shortDescription: 'Translate text to and from Morse code',
    category: 'text',
    icon: '\uD83D\uDCE1',
    isAI: false,
    isClientSide: true,
    keywords: ['morse code', 'morse translator', 'morse code converter', 'morse audio', 'dot dash'],
  },
  {
    slug: 'random-text-generator',
    name: 'Random Text Generator',
    description: 'Generate random words, sentences, paragraphs, names, email addresses, phone numbers, and addresses for testing and mockup purposes. Free random data generator.',
    shortDescription: 'Generate random text and mock data',
    category: 'text',
    icon: '\uD83C\uDFB2',
    isAI: false,
    isClientSide: true,
    keywords: ['random text', 'random generator', 'mock data', 'test data', 'random names', 'random emails'],
  },
  {
    slug: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat text N times with custom separator, prefix, suffix, and numbering options. Choose from various separators and number formats. Free online text repeater tool.',
    shortDescription: 'Repeat text with custom separators and numbering',
    category: 'text',
    icon: '\uD83D\uDD01',
    isAI: false,
    isClientSide: true,
    keywords: ['text repeater', 'repeat text', 'text multiplier', 'copy paste repeat', 'duplicate text'],
  },
  {
    slug: 'text-truncator',
    name: 'Text Truncator',
    description: 'Truncate text by characters, words, or sentences with customizable ellipsis. Choose ellipsis position (start, middle, end) and preserve whole words. Free text truncation tool.',
    shortDescription: 'Truncate text by characters, words, or sentences',
    category: 'text',
    icon: '\u2702\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['text truncator', 'truncate text', 'shorten text', 'text cutter', 'text ellipsis'],
  },
]
