import { Tool } from '@/types/tool'

export const textTools: Tool[] = [
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text. Estimate reading time. Free online word counter tool for writers and students.',
    shortDescription: 'Count words, characters, and more',
    category: 'text',
    icon: '\uD83D\uDD22',
    isAI: false,
    isClientSide: true,
    keywords: ['word counter', 'character counter', 'text counter', 'word count'],
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case and more. Free online text case converter.',
    shortDescription: 'Convert text between different cases',
    category: 'text',
    icon: 'Aa',
    isAI: false,
    isClientSide: true,
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake case'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate clean URL slugs from any text. Remove special characters, handle accents, and create SEO-friendly URLs. Free online slug generator.',
    shortDescription: 'Generate URL-friendly slugs from text',
    category: 'text',
    icon: '\uD83D\uDD17',
    isAI: false,
    isClientSide: true,
    keywords: ['slug generator', 'url slug', 'permalink', 'seo url'],
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and find differences. Highlight additions, deletions, and changes line by line. Free online text comparison tool.',
    shortDescription: 'Compare two texts and find differences',
    category: 'text',
    icon: '\uD83D\uDCCA',
    isAI: false,
    isClientSide: true,
    keywords: ['text diff', 'text compare', 'diff checker', 'find differences'],
  },
  {
    slug: 'html-entity-codec',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode special characters to HTML entities or decode HTML entities back to text. Supports named and numeric entities. Free online tool.',
    shortDescription: 'Encode and decode HTML entities',
    category: 'text',
    icon: '&lt;',
    isAI: false,
    isClientSide: true,
    keywords: ['html entity', 'html encode', 'html decode', 'special characters'],
  },
  {
    slug: 'text-to-binary',
    name: 'Text to Binary Converter',
    description: 'Convert text to binary, hexadecimal, or octal and vice versa. Free online text to binary converter with multiple encoding formats.',
    shortDescription: 'Convert text to binary, hex, or octal',
    category: 'text',
    icon: '\uD83D\uDCBB',
    isAI: false,
    isClientSide: true,
    keywords: ['text to binary', 'binary converter', 'hex converter', 'octal converter'],
    metaTitle: {
      az: 'Mətn-Binary Çevirici — Binary, Hex, Oktal | Pulsuz',
      en: 'Text to Binary — Binary, Hex, Octal Converter',
      tr: 'Metin-Binary — İkili, Onaltılı, Sekizli Çevirici',
      ru: 'Конвертер Текст-Двоичный — Binary, Hex, Octal',
    },
    metaDescription: {
      az: 'Mətni binary (ikilik), hex (onaltılıq) və ya oktal (səkkizlik) koda çevir — və ya əksinə. Developerlər və öyrənənlər üçün pulsuz alət.',
      en: 'Convert text to binary, hex, or octal — or back. Supports ASCII, UTF-8. Free browser tool for developers and students learning encoding.',
      tr: 'Metni ikili, on altılı veya sekizlik koda dönüştür veya tam tersi. ASCII, UTF-8 desteği. Geliştirici ve öğrenciler için ücretsiz.',
      ru: 'Конвертируй текст в двоичный, шестнадцатеричный или восьмеричный код — и обратно. ASCII, UTF-8. Для разработчиков.',
    },
  },
  {
    slug: 'rot13-encoder',
    name: 'ROT13 Encoder/Decoder',
    description: 'Encode and decode text using ROT13 Caesar cipher. Supports custom shift values from 1 to 25. Free online ROT13 encoder tool.',
    shortDescription: 'ROT13 and Caesar cipher encoder/decoder',
    category: 'text',
    icon: '\uD83D\uDD04',
    isAI: false,
    isClientSide: true,
    keywords: ['rot13', 'caesar cipher', 'rot13 encoder', 'cipher decoder'],
    metaTitle: {
      az: 'ROT13 Sezar Şifri — Kodla/Dekodla, 1-25 Sürmə',
      en: 'ROT13 & Caesar Cipher — Encode/Decode, Shift 1\u201325',
      tr: 'ROT13 Sezar Şifresi — Kodla/Çöz, 1\u201325 Kaydırma',
      ru: 'ROT13 Шифр Цезаря — Кодируй/Декодируй, 1\u201325',
    },
    metaDescription: {
      az: 'ROT13 ilə mətni kodla və ya dekod et. Xüsusi sürmə dəyəri (1-25) ilə Sezar şifri. Klassik kriptoqrafiya üçün pulsuz brauzer aləti.',
      en: 'Encode and decode text with ROT13 or any Caesar cipher shift (1\u201325). Free browser tool for classic cryptography and CTF puzzles.',
      tr: 'ROT13 veya herhangi bir Sezar şifresi kaydırmasıyla (1\u201325) metni kodla ve çöz. Klasik kriptografi için ücretsiz tarayıcı aracı.',
      ru: 'Кодируй и декодируй текст шифром ROT13 или любым сдвигом Цезаря (1\u201325). Для классической криптографии и CTF.',
    },
  },
  {
    slug: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Focus timer using the Pomodoro Technique. 25-minute work sessions with 5-minute breaks. Sound notifications and session tracking. Free online timer.',
    shortDescription: '25/5 minute work/break focus timer',
    category: 'text',
    icon: '\u23F1\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['pomodoro timer', 'focus timer', 'work timer', 'productivity timer'],
  },
  {
    slug: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to speech using the Web Speech API. Choose from available voices, adjust speed, pitch, and volume. Free online text-to-speech reader.',
    shortDescription: 'Read text aloud with voice controls',
    category: 'text',
    icon: '\uD83D\uDD0A',
    isAI: false,
    isClientSide: true,
    keywords: ['text to speech', 'tts', 'read aloud', 'speech synthesis', 'voice reader'],
    metaTitle: {
      az: 'Mətnə Səs — Pulsuz Onlayn Text-to-Speech',
      en: 'Free Text to Speech — Online, Instant, No Signup',
      tr: 'Metni Sese Dönüştürücü — Ücretsiz, Anlık',
      ru: 'Онлайн Озвучка Текста — Бесплатно, Без Установки',
    },
    metaDescription: {
      az: 'Mətnini brauzerində nitqə çevir — səs, sürət və ton seç. AZ, EN, RU, TR dəstəyi. Qeydiyyat yoxdur, fayl yüklənmir.',
      en: 'Read text aloud in your browser — pick voice, speed, and pitch. Supports English, Russian, Turkish, Azerbaijani. No signup, instant playback.',
      tr: 'Metni tarayıcında sese dönüştür — ses, hız ve ton seç. TR, EN, RU, AZ desteği. Kayıt yok, anında dinle.',
      ru: 'Озвучь текст в браузере — выбери голос, скорость и тон. Поддержка русского, английского, турецкого, азербайджанского.',
    },
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, words, sentences, paragraphs, and lines. View reading time, speaking time, character frequency, and more. Free detailed text analysis tool.',
    shortDescription: 'Detailed character and text statistics',
    category: 'text',
    icon: '\uD83D\uDD24',
    isAI: false,
    isClientSide: true,
    keywords: ['character counter', 'letter counter', 'text statistics', 'reading time', 'speaking time'],
  },
  {
    slug: 'find-and-replace',
    name: 'Find and Replace',
    description: 'Find and replace text with regex support, case sensitivity, and whole word matching. Highlights all matches in real-time. Free online find and replace tool.',
    shortDescription: 'Find and replace text with regex support',
    category: 'text',
    icon: '\uD83D\uDD0D',
    isAI: false,
    isClientSide: true,
    keywords: ['find and replace', 'search replace', 'text replace', 'regex replace', 'find text'],
  },
  {
    slug: 'morse-code',
    name: 'Morse Code Translator',
    description: 'Convert text to Morse code and back. Audio playback, reference chart, and bidirectional translation included. Free online Morse code translator.',
    shortDescription: 'Translate text to and from Morse code',
    category: 'text',
    icon: '\uD83D\uDCE1',
    isAI: false,
    isClientSide: true,
    keywords: ['morse code', 'morse translator', 'morse code converter', 'morse audio', 'dot dash'],
  },
  {
    slug: 'random-text-generator',
    name: 'Random Text Generator',
    description: 'Generate random words, sentences, paragraphs, names, email addresses, phone numbers, and addresses for testing and mockup purposes. Free random data generator.',
    shortDescription: 'Generate random text and mock data',
    category: 'text',
    icon: '\uD83C\uDFB2',
    isAI: false,
    isClientSide: true,
    keywords: ['random text', 'random generator', 'mock data', 'test data', 'random names', 'random emails'],
    metaTitle: {
      az: 'Təsadüfi Mətn — Söz, Cümlə, Ad, Email, Telefon',
      en: 'Random Text Generator — Words, Names, Emails, Phones',
      tr: 'Rastgele Metin — Kelime, Cümle, İsim, E-posta, Telefon',
      ru: 'Генератор Случайного Текста — Слова, Имена, Email',
    },
    metaDescription: {
      az: 'Testlər və maketlər üçün təsadüfi söz, cümlə, paraqraf, ad, email, telefon yaradır. Kopyala-yapışdır, toplu ixrac mümkündür.',
      en: 'Generate random words, sentences, paragraphs, names, emails, and phone numbers for tests and mockups. Copy-paste friendly, bulk export.',
      tr: 'Test ve maketler için rastgele kelime, cümle, paragraf, isim, e-posta ve telefon numarası üret. Kopyala-yapıştır, toplu dışa aktar.',
      ru: 'Генерируй случайные слова, предложения, абзацы, имена, email и телефоны для тестов и макетов. Копирование и массовый экспорт.',
    },
  },
  {
    slug: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat text N times with custom separator, prefix, suffix, and numbering options. Choose from various separators and number formats. Free online text repeater tool.',
    shortDescription: 'Repeat text with custom separators and numbering',
    category: 'text',
    icon: '\uD83D\uDD01',
    isAI: false,
    isClientSide: true,
    keywords: ['text repeater', 'repeat text', 'text multiplier', 'copy paste repeat', 'duplicate text'],
  },
  {
    slug: 'text-truncator',
    name: 'Text Truncator',
    description: 'Truncate text by characters, words, or sentences with customizable ellipsis. Choose ellipsis position (start, middle, end) and preserve whole words. Free text truncation tool.',
    shortDescription: 'Truncate text by characters, words, or sentences',
    category: 'text',
    icon: '\u2702\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['text truncator', 'truncate text', 'shorten text', 'text cutter', 'text ellipsis'],
  },
  {
    slug: 'hashtag-generator',
    name: 'Hashtag Generator',
    description: 'Generate hashtags from keywords with multiple styles. Browse popular hashtag presets by category. Copy individual or all hashtags. Free online hashtag generator for social media.',
    shortDescription: 'Generate hashtags from keywords for social media',
    category: 'text',
    icon: '#',
    isAI: false,
    isClientSide: true,
    keywords: ['hashtag generator', 'hashtag maker', 'instagram hashtags', 'social media hashtags', 'generate hashtags'],
  },
  {
    slug: 'readability-checker',
    name: 'Readability Checker',
    description: 'Analyze text readability with Flesch-Kincaid score, grade level, and Gunning Fog index. Get detailed statistics on word complexity and sentence length. Free readability tool.',
    shortDescription: 'Check text readability with Flesch-Kincaid score',
    category: 'text',
    icon: '\uD83D\uDCDA',
    isAI: false,
    isClientSide: true,
    keywords: ['readability checker', 'flesch kincaid', 'reading level', 'text analysis', 'readability score'],
  },
  {
    slug: 'lorem-ipsum-alternative',
    name: 'Lorem Ipsum Alternative',
    description: 'Generate fun placeholder text in different styles: Hipster, Corporate, Pirate, Space, Foodie, and Tech. Choose paragraphs, sentences, or words. Free creative filler text.',
    shortDescription: 'Generate themed placeholder text',
    category: 'text',
    icon: '\uD83C\uDFAD',
    isAI: false,
    isClientSide: true,
    keywords: ['lorem ipsum alternative', 'placeholder text', 'hipster ipsum', 'filler text', 'dummy text'],
  },
  {
    slug: 'text-to-handwriting',
    name: 'Text to Handwriting',
    description: 'Convert text to handwriting-style images with customizable fonts, ink colors, paper styles, and line spacing. Download as PNG. Free text to handwriting converter.',
    shortDescription: 'Convert text to handwriting-style images',
    category: 'text',
    icon: '\u270D\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['text to handwriting', 'handwriting generator', 'handwriting font', 'cursive text', 'handwritten text'],
  },
  {
    slug: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'Remove extra whitespace from text. Trim lines, collapse spaces, remove blank lines, tabs, and line breaks. Multiple cleanup options. Free whitespace cleaner.',
    shortDescription: 'Remove extra whitespace from text',
    category: 'text',
    icon: '\u2B1C',
    isAI: false,
    isClientSide: true,
    keywords: ['whitespace remover', 'remove spaces', 'trim whitespace', 'clean text', 'strip whitespace'],
  },
  {
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove duplicate lines from text. Case-sensitive or case-insensitive comparison, trim whitespace, and optional sorting. Free online duplicate line remover.',
    shortDescription: 'Remove duplicate lines from text',
    category: 'text',
    icon: '\uD83D\uDDD1\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['duplicate remover', 'remove duplicates', 'unique lines', 'deduplicate', 'duplicate line remover'],
  },
  {
    slug: 'twitter-char-counter',
    name: 'Twitter/X Character Counter',
    description: 'Count characters for Twitter/X posts with 280-character limit. Preview tweets, count hashtags, mentions, and URLs. URL shortening calculation included. Free tweet counter.',
    shortDescription: 'Count characters for tweets with preview',
    category: 'text',
    icon: '\uD83D\uDC26',
    isAI: false,
    isClientSide: true,
    keywords: ['twitter counter', 'tweet counter', 'character counter', 'x character limit', 'tweet length'],
  },
  {
    slug: 'instagram-caption-generator',
    name: 'Instagram Caption Generator',
    description: 'Generate Instagram captions with hashtags and emojis by category. Choose from Travel, Food, Fitness, Fashion, Nature, Business, Photography, and Tech. Free caption maker.',
    shortDescription: 'Generate Instagram captions with hashtags',
    category: 'text',
    icon: '\uD83D\uDCF8',
    isAI: false,
    isClientSide: true,
    keywords: ['instagram caption', 'caption generator', 'hashtag generator', 'instagram post', 'social media caption'],
  },
  {
    slug: 'stopwatch',
    name: 'Stopwatch',
    description: 'Precision stopwatch with lap tracking, best/worst lap highlighting, and millisecond accuracy. Start, stop, lap, and reset controls. Free online chronograph.',
    shortDescription: 'Millisecond precision stopwatch with laps',
    category: 'text',
    icon: '\u23F1\uFE0F',
    isAI: false,
    isClientSide: true,
    keywords: ['stopwatch', 'timer', 'chronograph', 'lap timer', 'millisecond timer'],
  },
]
